/**
 * 云盘链接数据（由 链接合集.xlsx 自动生成）
 * 共 800 条资源，覆盖 7 个分类。
 *
 * 字段说明：
 *   title      : 资源标题
 *   url        : 云盘链接
 *   category   : 分类
 *   source     : 网盘来源
 *   code       : 提取码（如有）
 *   note       : 备注 / 提示
 *   section    : 分类内分节（没有则为空）
 *   mangaUrl   : 对应漫画链接（仅部分动漫条目有）
 *   mangaTitle : 漫画标题/标签（如"怕寂寞的龍"，否则为"漫画"）
 */

var LINKS_DATA = [
  // ===== Windows工具 (48) =====
  // --- AI相关 ---
  { title: "AI语音合成声音克隆数字人生成 AigcPanelPro-0.11.0-win-x64.exe", url: "https://pan.quark.cn/s/a145ea94cc4e", category: "Windows工具", source: "夸克网盘", section: "AI相关" },
  { title: "AnythingLLMDesktop.exe", url: "https://pan.quark.cn/s/6578be374b24", category: "Windows工具", source: "夸克网盘", section: "AI相关" },
  { title: "CC-Switch-v3.16.5", url: "https://pan.quark.cn/s/dc0606c9e426", category: "Windows工具", source: "夸克网盘", section: "AI相关", note: "桌面应用，统一管理所有支持的 AI 工具，无需手动编辑配置文件" },
  { title: "Chatbox-1.9.8-Setup.exe", url: "https://pan.quark.cn/s/315cb6edca12", category: "Windows工具", source: "夸克网盘", section: "AI相关" },
  { title: "OllamaSetup.exe", url: "https://pan.quark.cn/s/0ea8f883d94f", category: "Windows工具", source: "夸克网盘", section: "AI相关" },
  { title: "声音克隆clone_voice", url: "https://pan.quark.cn/s/23928992dde0", category: "Windows工具", source: "夸克网盘", section: "AI相关" },
  { title: "Adobe全家桶 jh版", url: "https://pan.quark.cn/s/09b30cb25fed", category: "Windows工具", source: "夸克网盘" },
  { title: "PDF处理工具 Stirling-PDF-win-installer.exe", url: "https://pan.quark.cn/s/92a0922b513c", category: "Windows工具", source: "夸克网盘" },
  { title: "Steam.exe", url: "https://pan.quark.cn/s/301da7888892", category: "Windows工具", source: "夸克网盘" },
  { title: "WPS2019各版本-永久授权", url: "https://pan.quark.cn/s/f5a4fc81a0db", category: "Windows工具", source: "夸克网盘" },
  { title: "cat-catch猫抓浏览器插件.zip", url: "https://pan.quark.cn/s/96329e034638", category: "Windows工具", source: "夸克网盘", note: "自动嗅探网页资源，如视频、图片" },
  { title: "windows激活工具 CMWTAT_Digital_2_7_2_0.exe", url: "https://pan.quark.cn/s/9925de65e01d", category: "Windows工具", source: "夸克网盘" },
  { title: "【PS笔刷】4000个", url: "https://pan.quark.cn/s/ae0535b0b134", category: "Windows工具", source: "夸克网盘" },
  { title: "下载工具 fdm_x64_setup.exe", url: "https://pan.quark.cn/s/561d5932a6ae", category: "Windows工具", source: "夸克网盘", note: "拉满网速的下载工具" },
  { title: "基于selenium可视化爬虫 EasySpider_0.6.3_Windows_x64.7z", url: "https://pan.quark.cn/s/d90e56549c6e", category: "Windows工具", source: "夸克网盘" },
  { title: "多平台直播录制DouyinLiveRecorder_v4.0.3", url: "https://pan.quark.cn/s/c4fdd0f66fa5", category: "Windows工具", source: "夸克网盘", note: "支持多平台值守直播录制" },
  { title: "小红书下载工具 XHS-Downloader_V2.4_Windows_X64.zip", url: "https://pan.quark.cn/s/802b5c9234e9", category: "Windows工具", source: "夸克网盘", note: "搭配提取链接脚本可以批量下载视频" },
  { title: "小红书批量提取链接脚本.7z", url: "https://pan.quark.cn/s/6b124eb03cad", category: "Windows工具", source: "夸克网盘" },
  { title: "局域网传输工具 LocalSend.zip", url: "https://pan.quark.cn/s/17fdace41f15", category: "Windows工具", source: "夸克网盘", note: "支持安卓、windows、linux、maxos" },
  { title: "屏幕录制工具Cap_0.4.71_x64-setup.exe", url: "https://pan.quark.cn/s/9b317895fa8e", category: "Windows工具", source: "夸克网盘" },
  { title: "开源ARK工具OpenArk64.exe", url: "https://pan.quark.cn/s/0e5c865dc018", category: "Windows工具", source: "夸克网盘", note: "杀毒、逆向、辅助编程" },
  { title: "开源阅读工具Readest", url: "https://pan.quark.cn/s/da19753a437c", category: "Windows工具", source: "夸克网盘" },
  { title: "弱口令字典.zip", url: "https://pan.quark.cn/s/2e3947df0363", category: "Windows工具", source: "夸克网盘" },
  { title: "影刀RPA ShadowBot-5.25.52-x86.exe", url: "https://pan.quark.cn/s/067a91e5eb09", category: "Windows工具", source: "夸克网盘" },
  { title: "找文件 Everything-1.4.1.x64-Setup.exe", url: "https://pan.quark.cn/s/1eed54000f25", category: "Windows工具", source: "夸克网盘", note: "推荐一个好用的中转站：https://xfastapi.ai/register?aff=7V3LJKVSNKTF" },
  { title: "搭建自己的视频网站MoonTV", url: "https://pan.quark.cn/s/162fad724be5", category: "Windows工具", source: "夸克网盘", note: "自带视频源" },
  { title: "文件格式转换FileConverter-2.1-x64", url: "https://pan.quark.cn/s/5ef3ddcfe9e1", category: "Windows工具", source: "夸克网盘" },
  { title: "歌词下载获取直链MusicLyricApp-win-x64.7z", url: "https://pan.quark.cn/s/f7165c7d21a9", category: "Windows工具", source: "夸克网盘", note: "歌词下载、音乐直链获取（需要cookie）" },
  { title: "照片处理成证件照LiYing", url: "https://pan.quark.cn/s/3952c9b1d3fa", category: "Windows工具", source: "夸克网盘", note: "上传普通照片转证件照" },
  { title: "神秘的pdf-pdftris.pdf", url: "https://pan.quark.cn/s/3c8a575fc06e", category: "Windows工具", source: "夸克网盘" },
  { title: "米哈游人工桌面 N0vaDesktop_2.2.1.3_mihoyo.exe", url: "https://pan.quark.cn/s/5abe83fae502", category: "Windows工具", source: "夸克网盘" },
  { title: "系统优化工具Dism++10.1.1002.1B", url: "https://pan.quark.cn/s/6a52ee6f0ba2", category: "Windows工具", source: "夸克网盘" },
  { title: "系统时间加速 OpenSpeedy-v1.6.2.zip", url: "https://pan.quark.cn/s/eb4033ea6a8f", category: "Windows工具", source: "夸克网盘", note: "打单机游戏时间加速，也可以加速百度网盘下载" },
  { title: "解压用 7z2409-x64.exe", url: "https://pan.quark.cn/s/3501b6b8a76d", category: "Windows工具", source: "夸克网盘" },
  { title: "订阅信息源Folo-0.6.2", url: "https://pan.quark.cn/s/3ea144d76c51", category: "Windows工具", source: "夸克网盘", note: "一个应用聚合信息源资讯" },
  { title: "超好用的桌面课程表(教室必备)", url: "https://pan.quark.cn/s/aae59c1672af", category: "Windows工具", source: "夸克网盘" },
  { title: "长期保存剪切板EcoPaste", url: "https://pan.quark.cn/s/00766b131075", category: "Windows工具", source: "夸克网盘" },
  // --- 编程相关 ---
  { title: "Cursor Setup 0.43.5 - x64.exe", url: "https://pan.quark.cn/s/ef07aca66632", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "OCR学习 tesseract-ocr-w64-setup-5.4.0.20240606.exe", url: "https://pan.quark.cn/s/e143ad0d514a", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "WindsurfUserSetup-x64-1.0.5.exe", url: "https://pan.quark.cn/s/30be023395b3", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "android-studio-2024.2.1.12-windows.exe", url: "https://pan.quark.cn/s/6df251eab710", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "markdown编辑器", url: "https://pan.quark.cn/s/d5bb9371bfcd", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "pycharm-professional-2024.1.7", url: "https://pan.quark.cn/s/67b79275e4b0", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "python-3.12.9-amd64", url: "https://pan.quark.cn/s/1fc573b4e3e4", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "selenium浏览器驱动 chromedriver-win64.zip", url: "https://pan.quark.cn/s/31652c1352bf", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "全家桶激活脚本-Win系统.zip", url: "https://pan.quark.cn/s/49ca9568e7ba", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "环境切换 Miniconda3-latest-Windows-x86_64.exe", url: "https://pan.quark.cn/s/8628eb69b186", category: "Windows工具", source: "夸克网盘", section: "编程相关" },
  { title: "轻量级编辑器 npp.8.7.7.Installer.x64.exe", url: "https://pan.quark.cn/s/9d45806231b6", category: "Windows工具", source: "夸克网盘", section: "编程相关" },

  // ===== 剧集 (64) =====
  { title: "9号秘事.全9季+特别篇.中英双语", url: "https://pan.quark.cn/s/db82a8dfc4e5", category: "剧集", source: "夸克网盘" },
  { title: "A 爱，死亡和机器人 1-4季 内封+内嵌字幕 4K+1080P", url: "https://pan.quark.cn/s/b1e52da3f8d1", category: "剧集", source: "夸克网盘" },
  { title: "B 别对我说谎lie to me　1-3季", url: "https://pan.quark.cn/s/fa6352578fa8", category: "剧集", source: "夸克网盘" },
  { title: "F辐射2（2025）", url: "https://pan.quark.cn/s/490eaf2a1660", category: "剧集", source: "夸克网盘" },
  { title: "G 哥谭 1-5季合集 1080P 内嵌简英字幕", url: "https://pan.quark.cn/s/8b14807efd1f", category: "剧集", source: "夸克网盘" },
  { title: "G 怪奇物语 1-4季", url: "https://pan.quark.cn/s/22eeb23041b4", category: "剧集", source: "夸克网盘" },
  { title: "H 黑袍纠察队（2019）1-4季+V世代+劣迹 4K", url: "https://pan.quark.cn/s/01cba586adf7", category: "剧集", source: "夸克网盘" },
  { title: "J 经常请吃饭的漂亮姐姐（2018）全16集", url: "https://pan.quark.cn/s/bf2b7814cadb", category: "剧集", source: "夸克网盘" },
  { title: "J 绝命毒师 1-5季 附续命之徒+绝不折中 内封字幕", url: "https://pan.quark.cn/s/1533437ec138", category: "剧集", source: "夸克网盘" },
  { title: "L 轮到你了（2019）全20集 内封繁中字幕 1080P", url: "https://pan.quark.cn/s/603ea4cbde56", category: "剧集", source: "夸克网盘" },
  { title: "M 摩登家庭1-11季 铂金珍藏版", url: "https://pan.quark.cn/s/4ba9d89c5e9c", category: "剧集", source: "夸克网盘" },
  { title: "Q权欲之巅", url: "https://pan.quark.cn/s/315286758ec5", category: "剧集", source: "夸克网盘" },
  { title: "S 神盾局特工 1-7季", url: "https://pan.quark.cn/s/ba2d9ff4c74c", category: "剧集", source: "夸克网盘" },
  { title: "W我的天才女友1-4季（2018-2024）1080P", url: "https://pan.quark.cn/s/7fe1dbc12db2", category: "剧集", source: "夸克网盘" },
  { title: "X 行骗天下JP 电影+电视剧合集 内封+内嵌字幕 1080P", url: "https://pan.quark.cn/s/76ddb2c0a4a3", category: "剧集", source: "夸克网盘" },
  { title: "X《小谢尔顿》（2017-2024）1-7季全 1080P 中字", url: "https://pan.quark.cn/s/e3d5563c37bf", category: "剧集", source: "夸克网盘" },
  { title: "Y 鱿鱼游戏 1-3季 硬字幕+软字幕 4K+1080P", url: "https://pan.quark.cn/s/157420868fa6", category: "剧集", source: "夸克网盘" },
  { title: "Y-月光骑士", url: "https://pan.quark.cn/s/6461c9314091", category: "剧集", source: "夸克网盘" },
  { title: "Z 纸牌屋 1-6季 1080P", url: "https://pan.quark.cn/s/3c31fbe171e4", category: "剧集", source: "夸克网盘" },
  { title: "Z【美剧】最后生还者", url: "https://pan.quark.cn/s/35353c0a91b2", category: "剧集", source: "夸克网盘" },
  { title: "[弥留之国的爱丽丝 S01-S03][全集][日剧][漫画]", url: "https://pan.quark.cn/s/46fc25d6556c", category: "剧集", source: "夸克网盘", note: "附漫画 更新第三季" },
  { title: "《变形金刚系列》七部合集 [4K HDR 蓝光] 国英双语音轨 [内封精品特效字幕]【典藏版】235G", url: "https://pan.quark.cn/s/705306246209", category: "剧集", source: "夸克网盘" },
  { title: "《老友记》1-10季+重聚特辑1080P 内嵌硬字幕版", url: "https://pan.quark.cn/s/0cc5f623fe9d", category: "剧集", source: "夸克网盘" },
  { title: "【日剧】人生删除事务所.2018.全8集", url: "https://pan.quark.cn/s/239e9b959548", category: "剧集", source: "夸克网盘" },
  { title: "【韩剧】给你宇宙", url: "https://pan.quark.cn/s/78931beb1e73", category: "剧集", source: "夸克网盘" },
  { title: "了不起的麦瑟尔夫人.全5季", url: "https://pan.quark.cn/s/f0e0e795b5ce", category: "剧集", source: "夸克网盘" },
  { title: "人生切割术 第一季", url: "https://pan.quark.cn/s/1fbab34d92de", category: "剧集", source: "夸克网盘" },
  { title: "依然闪亮", url: "https://pan.quark.cn/s/8b445d7458b5", category: "剧集", source: "夸克网盘" },
  { title: "假面骑士·系列最全资源·合集(最新歌查德+全系列番外+外传)", url: "https://pan.quark.cn/s/22a60d8c3a09", category: "剧集", source: "夸克网盘" },
  { title: "十角馆事件 十角館の殺人 (2024)", url: "https://pan.quark.cn/s/802dbc8f99f0", category: "剧集", source: "夸克网盘" },
  { title: "千谎百计.全3季.中英双字.1080P", url: "https://pan.quark.cn/s/8384017160ec", category: "剧集", source: "夸克网盘" },
  { title: "半泽直树.全2季+特别篇.特效字幕+小说5集全", url: "https://pan.quark.cn/s/e1edc863feed", category: "剧集", source: "夸克网盘", note: "附小说" },
  { title: "唐顿庄园 1-6季全集", url: "https://pan.quark.cn/s/2a5ad7aae1d8", category: "剧集", source: "夸克网盘" },
  { title: "夜魔侠", url: "https://pan.quark.cn/s/60bc6c2e2b4a", category: "剧集", source: "夸克网盘" },
  { title: "失控 Driven 第1-3季", url: "https://pan.quark.cn/s/e68dd6e8b663", category: "剧集", source: "夸克网盘" },
  { title: "幸福伽菜子(加奈子)的快乐杀手生活 (2025) 全6集 日语中字  喜剧动作", url: "https://pan.quark.cn/s/714312da463e", category: "剧集", source: "夸克网盘", note: "附漫画" },
  { title: "心灵的声音2016", url: "https://pan.quark.cn/s/41d0ba7686c7", category: "剧集", source: "夸克网盘" },
  { title: "心里的声音 마음의 소리 (2016)", url: "https://pan.quark.cn/s/b9714b2ecdf4", category: "剧集", source: "夸克网盘" },
  { title: "恋恋洗衣店 みなと商事コインランドリー 1-2季", url: "https://pan.quark.cn/s/5032f16a52f9", category: "剧集", source: "夸克网盘" },
  { title: "恋爱何必认真？ 恋なんて、本気でやってどうするの？ (2022)", url: "https://pan.quark.cn/s/03e6baa22daf", category: "剧集", source: "夸克网盘" },
  { title: "惊奇的传闻 1-2季 1080P 韩语中字【全集】", url: "https://pan.quark.cn/s/566e976b1514", category: "剧集", source: "夸克网盘" },
  { title: "我会找到你（2026）", url: "https://pan.quark.cn/s/5aa3b7a17e00", category: "剧集", source: "夸克网盘" },
  { title: "新进职员姜会长(2026)", url: "https://pan.quark.cn/s/306393a4593b", category: "剧集", source: "夸克网盘" },
  { title: "昨夜的咖喱 明日的面包 昨夜のカレー 明日のパン (2014)", url: "https://pan.quark.cn/s/e0424122f811", category: "剧集", source: "夸克网盘" },
  { title: "暗影蜘蛛侠", url: "https://pan.quark.cn/s/68e49483efa1", category: "剧集", source: "夸克网盘" },
  { title: "格林 S01-06", url: "https://pan.quark.cn/s/7d3250984dca", category: "剧集", source: "夸克网盘" },
  { title: "犯罪心理 1-17季", url: "https://pan.quark.cn/s/14214d93ea34", category: "剧集", source: "夸克网盘" },
  { title: "生活大爆炸.全12季.中英双字", url: "https://pan.quark.cn/s/779c0f88e9a9", category: "剧集", source: "夸克网盘" },
  { title: "破产姐妹1-6季全 1080P（未删减）", url: "https://pan.quark.cn/s/f61e94bccc97", category: "剧集", source: "夸克网盘" },
  { title: "神探夏洛克 1-4季全集 中英双字", url: "https://pan.quark.cn/s/ae584a3903f1", category: "剧集", source: "夸克网盘" },
  { title: "福尔摩斯：基本演绎法.全7季.中英双字.1080P", url: "https://pan.quark.cn/s/218646a71ab7", category: "剧集", source: "夸克网盘" },
  { title: "美国恐怖故事（1-12季全）American Horror Story", url: "https://pan.quark.cn/s/aa79fa57db2a", category: "剧集", source: "夸克网盘" },
  { title: "苦尽柑来遇见你 폭싹 속았수다 (2025)", url: "https://pan.quark.cn/s/a1cdd73c7943", category: "剧集", source: "夸克网盘" },
  { title: "西部世界.全4季", url: "https://pan.quark.cn/s/c4fcb0695ec0", category: "剧集", source: "夸克网盘" },
  { title: "超感猎杀 1-2季", url: "https://pan.quark.cn/s/d55ea895eedf", category: "剧集", source: "夸克网盘" },
  { title: "达顿牧场", url: "https://pan.quark.cn/s/dacd4f12a571", category: "剧集", source: "夸克网盘" },
  { title: "逃避虽可耻但有用 逃げるは恥だが役に立つ (2016)", url: "https://pan.quark.cn/s/715a058c7fb2", category: "剧集", source: "夸克网盘" },
  { title: "韩剧-S神与律师事务所", url: "https://pan.quark.cn/s/1bf5f0f761e9", category: "剧集", source: "夸克网盘" },
  { title: "风骚律师 1-6季", url: "https://pan.quark.cn/s/cdc5847bf4e6", category: "剧集", source: "夸克网盘" },
  { title: "黑镜", url: "https://pan.quark.cn/s/770a2f701b0c", category: "剧集", source: "夸克网盘" },
  // --- 少量电影 ---
  { title: "新·奥特曼", url: "https://pan.quark.cn/s/f761ca0d9513", category: "剧集", source: "夸克网盘", section: "少量电影" },
  { title: "环太平洋", url: "https://pan.quark.cn/s/76c850a4572b", category: "剧集", source: "夸克网盘", section: "少量电影" },
  { title: "花束般的恋爱(2021) 4K 国语+日语", url: "https://pan.quark.cn/s/32f5a887f34f", category: "剧集", source: "夸克网盘", section: "少量电影" },
  { title: "重出江湖", url: "https://pan.quark.cn/s/2de131684d21", category: "剧集", source: "夸克网盘", section: "少量电影" },

  // ===== 动漫 (379) =====
  { title: "#COMPASS2.0 战斗天赋解析系统", url: "https://pan.quark.cn/s/fb90394159e6", category: "动漫", source: "夸克网盘" },
  { title: "1992 幽游白书", url: "https://pan.quark.cn/s/11b8337cbe0d", category: "动漫", source: "夸克网盘" },
  { title: "2.5次元的诱惑", url: "https://pan.quark.cn/s/39b1492fdb20", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "29岁单身冒险家的日常", url: "https://pan.quark.cn/s/ff063ba0f509", category: "动漫", source: "夸克网盘" },
  { title: "3年Z班银八老师", url: "https://pan.quark.cn/s/c0af6b27b104", category: "动漫", source: "夸克网盘" },
  { title: "4个人各自有着自己的秘密", url: "https://pan.quark.cn/s/2be376fbb807", category: "动漫", source: "夸克网盘" },
  { title: "86 -不存在的战区-", url: "https://pan.quark.cn/s/95a85c9615cd", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "9-nine- 支配者的王冠", url: "https://pan.quark.cn/s/c5a817268a54", category: "动漫", source: "夸克网盘" },
  { title: "Angel Beats 天使的心跳", url: "https://pan.quark.cn/s/6f366cd3a3ed", category: "动漫", source: "夸克网盘" },
  { title: "BEASTARS 动物狂想曲", url: "https://pan.quark.cn/s/53dd19286756", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "BLEACH 死神", url: "https://pan.quark.cn/s/0389562272b6", category: "动漫", source: "夸克网盘" },
  { title: "BanG Dream!", url: "https://pan.quark.cn/s/b7c7200f92d9", category: "动漫", source: "夸克网盘", note: "It's MyGo!!!!! Ave mujica Morfonication 少女乐团派对" },
  { title: "Charlotte 夏洛特", url: "https://pan.quark.cn/s/7553283fe271", category: "动漫", source: "夸克网盘" },
  { title: "Citrus~柑橘味香气~", url: "https://pan.quark.cn/s/60cd88bad95d", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "Clannad 团子大家族", url: "https://pan.quark.cn/s/0ef4a8dceaac", category: "动漫", source: "夸克网盘" },
  { title: "Clevatess-魔-S之-王-与Y儿.与-.S之-勇-者-", url: "https://pan.quark.cn/s/65b12b301c56", category: "动漫", source: "夸克网盘" },
  { title: "DARK MOON -黑之月：月之祭坛-", url: "https://pan.quark.cn/s/ee831bf12643", category: "动漫", source: "夸克网盘" },
  { title: "DARLING in the FRANXX（国家队 比翼之吻 ）", url: "https://pan.quark.cn/s/cb20ec2e07cf", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "EVA 新世纪福音战士", url: "https://pan.quark.cn/s/27b1182ea60c", category: "动漫", source: "夸克网盘" },
  { title: "Fate／strange Fake 命運-奇异贗品", url: "https://pan.quark.cn/s/e5259f9a61aa", category: "动漫", source: "夸克网盘" },
  { title: "GIRLS BAND CRY／哭泣少女乐队", url: "https://pan.quark.cn/s/f2934a115e50", category: "动漫", source: "夸克网盘", note: "附音乐" },
  { title: "Gamers 电玩咖!", url: "https://pan.quark.cn/s/21233c139d9d", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "H 欢迎来到实力主义至上教室", url: "https://pan.quark.cn/s/29659050411f", category: "动漫", source: "夸克网盘", note: "带小说" },
  { title: "H 海贼王", url: "https://pan.quark.cn/s/e6d264aad1bb", category: "动漫", source: "夸克网盘", note: "至1161 附剧场版 真人版" },
  { title: "IS〈无限斯特拉托斯〉Infinite Stratos", url: "https://pan.quark.cn/s/d94004789e93", category: "动漫", source: "夸克网盘" },
  { title: "JOJO的奇.妙.冒.险", url: "https://pan.quark.cn/s/135f8e723aca", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "Just Because!", url: "https://pan.quark.cn/s/f79a8e71fddb", category: "动漫", source: "夸克网盘" },
  { title: "KILL la KILL 斩服少女 双斩少女", url: "https://pan.quark.cn/s/75d7126a8f53", category: "动漫", source: "夸克网盘" },
  { title: "Love Live!", url: "https://pan.quark.cn/s/43e2493bc04a", category: "动漫", source: "夸克网盘", note: "aqours superstar 虹咲" },
  { title: "LoveLive！莲之空女学院学园偶像俱乐部 Bloom Garden Party", url: "https://pan.quark.cn/s/7789af0194b1", category: "动漫", source: "夸克网盘" },
  { title: "Lycoris Recoil 莉可丽丝", url: "https://pan.quark.cn/s/ef1429f2fd4c", category: "动漫", source: "夸克网盘" },
  { title: "M 迷宫饭", url: "https://pan.quark.cn/s/c2464169c30f", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "NANA 娜娜 世界上的另一个我 ナナ", url: "https://pan.quark.cn/s/70507b9aa541", category: "动漫", source: "夸克网盘" },
  { title: "OVERLORD 不死者之王", url: "https://pan.quark.cn/s/b3caf9c0d259", category: "动漫", source: "夸克网盘", note: "附漫画 小说" },
  { title: "Q 七龙珠 全系列 +漫画", url: "https://pan.quark.cn/s/3dba52343201", category: "动漫", source: "夸克网盘", note: "附漫画 剧场版" },
  { title: "R  弱势角色友崎君／弱角友崎同学 附小说", url: "https://pan.quark.cn/s/22892fbd210d", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "Re：从零开始的异世界生活", url: "https://pan.quark.cn/s/14255a8eda65", category: "动漫", source: "夸克网盘", note: "带小说" },
  { title: "SSSS.系列", url: "https://pan.quark.cn/s/5f0175f31788", category: "动漫", source: "夸克网盘" },
  { title: "School Days 日在校园", url: "https://pan.quark.cn/s/2ecab36079eb", category: "动漫", source: "夸克网盘" },
  { title: "W 我心里危险的东西", url: "https://pan.quark.cn/s/1d8b6121201d", category: "动漫", source: "夸克网盘" },
  { title: "Z 葬送的芙莉莲", url: "https://pan.quark.cn/s/beab97850e84", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "mono女孩", url: "https://pan.quark.cn/s/a7060051ac55", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "pop子和pipi美的日常", url: "https://pan.quark.cn/s/035ddc0eb7f5", category: "动漫", source: "夸克网盘" },
  { title: "一叠间漫画咖啡屋生活！", url: "https://pan.quark.cn/s/180a42f25be7", category: "动漫", source: "夸克网盘" },
  { title: "一拳超人", url: "https://pan.quark.cn/s/5ff18ad1a310", category: "动漫", source: "夸克网盘" },
  { title: "一杆青空／空色Utility", url: "https://pan.quark.cn/s/20a99dd68099", category: "动漫", source: "夸克网盘" },
  { title: "一起一起这里那里", url: "https://pan.quark.cn/s/690ba2029da3", category: "动漫", source: "夸克网盘" },
  { title: "七大罪", url: "https://pan.quark.cn/s/8195882c3f4b", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "万事屋斋藤先生转生异世界", url: "https://pan.quark.cn/s/833d641830a0", category: "动漫", source: "夸克网盘" },
  { title: "三岁开始做王者／最强王者的第二人生", url: "https://pan.quark.cn/s/44d54a12a0db", category: "动漫", source: "夸克网盘" },
  { title: "不当哥哥了！／别当欧尼酱了！", url: "https://pan.quark.cn/s/fb2a4f3c3efe", category: "动漫", source: "夸克网盘" },
  { title: "不时轻声地以俄语遮羞的邻座艾莉同学", url: "https://pan.quark.cn/s/bfe5bbcbab73", category: "动漫", source: "夸克网盘", note: "附小说漫画" },
  { title: "不要欺负我，长瀞同学", url: "https://pan.quark.cn/s/43d809d4e736", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "世界计划- 无法歌唱的初音未来", url: "https://pan.quark.cn/s/7f31fc5ca593", category: "动漫", source: "夸克网盘" },
  { title: "东京喰种", url: "https://pan.quark.cn/s/5130446f213f", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "东京复仇者", url: "https://pan.quark.cn/s/c90db3943905", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "东京猫猫 NEW～♡", url: "https://pan.quark.cn/s/04966990c1f2", category: "动漫", source: "夸克网盘" },
  { title: "中二病也要谈恋爱", url: "https://pan.quark.cn/s/dab12791923d", category: "动漫", source: "夸克网盘" },
  { title: "为美好的世界献上祝福。", url: "https://pan.quark.cn/s/56d1db282264", category: "动漫", source: "夸克网盘", note: "带小说" },
  { title: "主播女孩重度依赖", url: "https://pan.quark.cn/s/87f49119742b", category: "动漫", source: "夸克网盘" },
  { title: "久保同学不放过我", url: "https://pan.quark.cn/s/d8adbbb2c4a8", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "乡下大叔成为剑圣", url: "https://pan.quark.cn/s/48e0432b78d6", category: "动漫", source: "夸克网盘" },
  { title: "乱马½", url: "https://pan.quark.cn/s/2bafcd0feb44", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "五等分的新娘", url: "https://pan.quark.cn/s/c2164c4c8dce", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "伪恋", url: "https://pan.quark.cn/s/74066f6011fe", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "佐贺偶像是传奇", url: "https://pan.quark.cn/s/85d3c3b9f5d1", category: "动漫", source: "夸克网盘" },
  { title: "你与我最后的战场，亦或是世界起始的圣战", url: "https://pan.quark.cn/s/19ef2af1be27", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "俺物语", url: "https://pan.quark.cn/s/c293e759070f", category: "动漫", source: "夸克网盘" },
  { title: "偶像大师", url: "https://pan.quark.cn/s/e2859f4054c6", category: "动漫", source: "夸克网盘", note: "百万现场 灰姑娘" },
  { title: "偶像大师 闪耀色彩", url: "https://pan.quark.cn/s/664a0250b78b", category: "动漫", source: "夸克网盘" },
  { title: "僵尸百分百~变成僵尸之前想做的100件事~", url: "https://pan.quark.cn/s/8eba946a70fc", category: "动漫", source: "夸克网盘" },
  { title: "元祖！BanG Dream酱／元祖 小邦多利", url: "https://pan.quark.cn/s/8c917263488b", category: "动漫", source: "夸克网盘" },
  { title: "全修。", url: "https://pan.quark.cn/s/6c22decabb4e", category: "动漫", source: "夸克网盘" },
  { title: "全职猎人", url: "https://pan.quark.cn/s/7318c95157ca", category: "动漫", source: "夸克网盘" },
  { title: "公主大人，接下来是“拷问”时间", url: "https://pan.quark.cn/s/38f3c0fc7271", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "公鸡斗士", url: "https://pan.quark.cn/s/326111c4f239", category: "动漫", source: "夸克网盘" },
  { title: "六花的勇者", url: "https://pan.quark.cn/s/5801a3e83aa9", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "关于前辈很烦人的事", url: "https://pan.quark.cn/s/d904b89c7caf", category: "动漫", source: "夸克网盘" },
  { title: "关于我转生变成史莱姆这档事", url: "https://pan.quark.cn/s/f2f6514c3c25", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "关于虽然逃走的鱼很大、但钓上来的鱼却太大了这件事", url: "https://pan.quark.cn/s/6938569ec453", category: "动漫", source: "夸克网盘" },
  { title: "关于邻家的天使大人不知不觉把我惯成了废人这档子事", url: "https://pan.quark.cn/s/6b30a83c817b", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "冰之城墙", url: "https://pan.quark.cn/s/cb782a82f9b5", category: "动漫", source: "夸克网盘" },
  { title: "冰菓／冰果／Hyouka", url: "https://pan.quark.cn/s/2ad2c423b9ed", category: "动漫", source: "夸克网盘" },
  { title: "凉宫春日的忧郁", url: "https://pan.quark.cn/s/f3998f03d1fe", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "刀剑神域", url: "https://pan.quark.cn/s/1651f7439fa8", category: "动漫", source: "夸克网盘", note: "带小说 · GGO" },
  { title: "到了30岁还是处男，似乎会变成魔法师", url: "https://pan.quark.cn/s/83f7a2162398", category: "动漫", source: "夸克网盘" },
  { title: "剃须。然后捡到女高中生。", url: "https://pan.quark.cn/s/e97c1281f620", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "前桥魔女", url: "https://pan.quark.cn/s/896c218ec6f0", category: "动漫", source: "夸克网盘" },
  { title: "剑勇传说／九龙珠", url: "https://pan.quark.cn/s/8434449db0cf", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "加油！同期酱", url: "https://pan.quark.cn/s/59a4ca970bec", category: "动漫", source: "夸克网盘" },
  { title: "加速世界", url: "https://pan.quark.cn/s/c4585fc60088", category: "动漫", source: "夸克网盘" },
  { title: "勇者处刑", url: "https://pan.quark.cn/s/2bcdcfdfb060", category: "动漫", source: "夸克网盘" },
  { title: "北鬥の拳/新 北斗神拳 -FIST OF THE NORTH STAR-", url: "https://pan.quark.cn/s/2f863333c83e", category: "动漫", source: "夸克网盘" },
  { title: "反叛的鲁路修", url: "https://pan.quark.cn/s/86a8a2eea762", category: "动漫", source: "夸克网盘" },
  { title: "变态王子与不笑猫", url: "https://pan.quark.cn/s/978913711d62", category: "动漫", source: "夸克网盘" },
  { title: "古见同学有交流障碍症", url: "https://pan.quark.cn/s/b2ef7c8b87b6", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "只有我不存在的城市", url: "https://pan.quark.cn/s/410e110664f8", category: "动漫", source: "夸克网盘" },
  { title: "只有神知道的世界", url: "https://pan.quark.cn/s/a201c4fcc3a1", category: "动漫", source: "夸克网盘" },
  { title: "只要长得可爱，即使是变态你也喜欢吗", url: "https://pan.quark.cn/s/b87294390639", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "吊带袜天使", url: "https://pan.quark.cn/s/3c63cc351613", category: "动漫", source: "夸克网盘" },
  { title: "名侦探光之美少女", url: "https://pan.quark.cn/s/7fcc00b614bb", category: "动漫", source: "夸克网盘" },
  { title: "名侦探柯南", url: "https://pan.quark.cn/s/237ddbbc6a5c", category: "动漫", source: "夸克网盘", note: "剧场版" },
  { title: "吞噬魔物的冒险者", url: "https://pan.quark.cn/s/fb57ea03e56f", category: "动漫", source: "夸克网盘" },
  { title: "启示录酒店／末日后酒店", url: "https://pan.quark.cn/s/9170c04571a8", category: "动漫", source: "夸克网盘" },
  { title: "吹响吧！上低音号", url: "https://pan.quark.cn/s/316091da61b5", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "命运石之门", url: "https://pan.quark.cn/s/9c1965140b43", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "和山田进行LV.999的恋爱", url: "https://pan.quark.cn/s/118de53d759c", category: "动漫", source: "夸克网盘" },
  { title: "和班上第二可爱的女孩成为朋友", url: "https://pan.quark.cn/s/0b700c984d92", category: "动漫", source: "夸克网盘" },
  { title: "和青梅竹马之间不会有恋爱喜剧", url: "https://pan.quark.cn/s/41fffaa3704a", category: "动漫", source: "夸克网盘" },
  { title: "咒术回战 全系列 4K", url: "https://pan.quark.cn/s/e0221f748617", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "咒術廻戰", url: "https://pan.quark.cn/s/c3fbf2009c1e", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "喜欢的人忘记戴眼镜了", url: "https://pan.quark.cn/s/f8e4c1c16273", category: "动漫", source: "夸克网盘" },
  { title: "噗妮露是可爱史莱姆", url: "https://pan.quark.cn/s/b6138b7f348b", category: "动漫", source: "夸克网盘" },
  { title: "噬血狂袭", url: "https://pan.quark.cn/s/83d9f700b2c3", category: "动漫", source: "夸克网盘" },
  { title: "四月是你的谎言", url: "https://pan.quark.cn/s/dd03c5869dde", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "因为太怕痛就全点防御力了／怕痛的我，把防御力点满就对了。", url: "https://pan.quark.cn/s/bb78f2153c70", category: "动漫", source: "夸克网盘" },
  { title: "在下坂本，有何贵干", url: "https://pan.quark.cn/s/ccc0cb26201c", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "在冲绳喜欢上的女孩子方言讲太多太棘手了", url: "https://pan.quark.cn/s/a8ae5ea568d0", category: "动漫", source: "夸克网盘" },
  { title: "在地下城寻求邂逅是否搞错了什么", url: "https://pan.quark.cn/s/a2c78c931422", category: "动漫", source: "夸克网盘" },
  { title: "在魔王城说晚安", url: "https://pan.quark.cn/s/9f713f980c09", category: "动漫", source: "夸克网盘" },
  { title: "地狱乐", url: "https://pan.quark.cn/s/5a8cb9ada419", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "地狱少女", url: "https://pan.quark.cn/s/abe7d3f43871", category: "动漫", source: "夸克网盘" },
  { title: "地狱模式 ～喜欢速通游戏的玩家在废设定异世界无双～", url: "https://pan.quark.cn/s/370f80d00889", category: "动漫", source: "夸克网盘" },
  { title: "地缚少年花子君", url: "https://pan.quark.cn/s/95bfffae2965", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "坂.｜本.R.常／坂.本｜Days", url: "https://pan.quark.cn/s/b804c5c3c9c9", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "坂本日常／坂本Days", url: "https://pan.quark.cn/s/e99643cfd7d3", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "埃罗芒阿老师", url: "https://pan.quark.cn/s/814bd8cc52e3", category: "动漫", source: "夸克网盘" },
  { title: "堀与宫村", url: "https://pan.quark.cn/s/fd0c16bff3d0", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "境界的彼方", url: "https://pan.quark.cn/s/134eaf14d09b", category: "动漫", source: "夸克网盘" },
  { title: "复制品的我也会谈恋爱", url: "https://pan.quark.cn/s/0eb3435a3bbe", category: "动漫", source: "夸克网盘" },
  { title: "夏日口袋 Summer Pockets", url: "https://pan.quark.cn/s/860d3b89c3f5", category: "动漫", source: "夸克网盘" },
  { title: "夏日重现", url: "https://pan.quark.cn/s/5d5f52da2bf5", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "夏目友人帐", url: "https://pan.quark.cn/s/38f92493919b", category: "动漫", source: "夸克网盘", note: "带漫画 · 目前更新至26年4月番" },
  { title: "外星人姆姆", url: "https://pan.quark.cn/s/cbe404006777", category: "动漫", source: "夸克网盘" },
  { title: "夜樱家的大作战", url: "https://pan.quark.cn/s/09936b4f1f71", category: "动漫", source: "夸克网盘" },
  { title: "天使降临到了我身边!", url: "https://pan.quark.cn/s/e7688be6c20a", category: "动漫", source: "夸克网盘" },
  { title: "失忆投捕／忘却Battery", url: "https://pan.quark.cn/s/46858f9dd24d", category: "动漫", source: "夸克网盘" },
  { title: "女仆小姐的贪吃日常", url: "https://pan.quark.cn/s/c224d50b9f3a", category: "动漫", source: "夸克网盘" },
  { title: "女神「异世界转生想成为什么", url: "https://pan.quark.cn/s/0318a61cf34a", category: "动漫", source: "夸克网盘" },
  { title: "女骑士成为蛮族新娘", url: "https://pan.quark.cn/s/26eb0b00c9ba", category: "动漫", source: "夸克网盘" },
  { title: "女高中生的无所事事", url: "https://pan.quark.cn/s/43488600643b", category: "动漫", source: "夸克网盘" },
  { title: "妖狐×仆SS", url: "https://pan.quark.cn/s/c96cc29a9126", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "婚姻剧毒", url: "https://pan.quark.cn/s/e61fed914c3c", category: "动漫", source: "夸克网盘", mangaUrl: "https://pan.quark.cn/s/27fec2c2d76a", mangaTitle: "婚姻劇毒" },
  { title: "婚戒物语", url: "https://pan.quark.cn/s/90d4b044f91f", category: "动漫", source: "夸克网盘" },
  { title: "孤独摇滚", url: "https://pan.quark.cn/s/e2b0e26e3475", category: "动漫", source: "夸克网盘" },
  { title: "学园孤岛", url: "https://pan.quark.cn/s/67465824fac4", category: "动漫", source: "夸克网盘" },
  { title: "学生会的一己之见", url: "https://pan.quark.cn/s/7dfad11cb36a", category: "动漫", source: "夸克网盘" },
  { title: "宅男腐女恋爱真难", url: "https://pan.quark.cn/s/04041e6cc642", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "宇崎学妹想要玩", url: "https://pan.quark.cn/s/48e9d3e530a2", category: "动漫", source: "夸克网盘" },
  { title: "守护甜心", url: "https://pan.quark.cn/s/bed4e69459af", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "安达与岛村（樱与抱月）", url: "https://pan.quark.cn/s/bb2e00a41b47", category: "动漫", source: "夸克网盘" },
  { title: "安逸領主的愉快領地防衛～", url: "https://pan.quark.cn/s/aaec76fa93ca", category: "动漫", source: "夸克网盘" },
  { title: "宝可梦 地平线", url: "https://pan.quark.cn/s/455ab07bff98", category: "动漫", source: "夸克网盘" },
  { title: "宫崎骏合集 蓝光REMUX原盘 国粤日多音轨 内封简繁中文字幕", url: "https://pan.quark.cn/s/e0cf97b2c8d4", category: "动漫", source: "夸克网盘", note: "侧耳倾听 风之谷 哈尔的移动城堡 龙猫 猫的报恩 起风了 千与千寻 天空之城 崖上的波妞" },
  { title: "宿命回响：命运节拍", url: "https://pan.quark.cn/s/0437d0ef9a7b", category: "动漫", source: "夸克网盘" },
  { title: "寒蝉鸣泣之时", url: "https://pan.quark.cn/s/36864bb48fea", category: "动漫", source: "夸克网盘" },
  { title: "对我垂涎欲滴的非人少女／想吃掉我的非人少女", url: "https://pan.quark.cn/s/10b2624594f1", category: "动漫", source: "夸克网盘" },
  { title: "小书痴的下克上", url: "https://pan.quark.cn/s/c2814b4a2379", category: "动漫", source: "夸克网盘" },
  { title: "小市民系列", url: "https://pan.quark.cn/s/43259150ed2d", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "小林家的龙女仆", url: "https://pan.quark.cn/s/de082f2e2fd1", category: "动漫", source: "夸克网盘", mangaUrl: "https://pan.quark.cn/s/66c5332275dd", mangaTitle: "怕寂寞的龍" },
  { title: "少女与战车", url: "https://pan.quark.cn/s/1ebaffce6a03", category: "动漫", source: "夸克网盘" },
  { title: "尖帽子的魔法工房", url: "https://pan.quark.cn/s/cf6c4d873e0d", category: "动漫", source: "夸克网盘" },
  { title: "工作细胞", url: "https://pan.quark.cn/s/052e1100ab1d", category: "动漫", source: "夸克网盘", note: "附真人版" },
  { title: "左撇子艾伦", url: "https://pan.quark.cn/s/ed3a1cf9b4ce", category: "动漫", source: "夸克网盘" },
  { title: "帝乃三姐妹原来很好搞定。", url: "https://pan.quark.cn/s/bef685d7dc0c", category: "动漫", source: "夸克网盘" },
  { title: "干物妹！小埋", url: "https://pan.quark.cn/s/97ea3a4c4c96", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "平凡职业造就世界最强", url: "https://pan.quark.cn/s/88535c51acce", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "幽灵音乐会：遗失的歌曲", url: "https://pan.quark.cn/s/055e63c45aec", category: "动漫", source: "夸克网盘" },
  { title: "库兹马唱歌的话家里哆啰啰", url: "https://pan.quark.cn/s/bb7f327037e7", category: "动漫", source: "夸克网盘" },
  { title: "异世界悠闲农家", url: "https://pan.quark.cn/s/e13496b8bfbd", category: "动漫", source: "夸克网盘" },
  { title: "异世界舅舅", url: "https://pan.quark.cn/s/f3036f294ab8", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "异国日记", url: "https://pan.quark.cn/s/a1184efb36f4", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "式守同学不只可爱而已／我家女友可不止可爱呢", url: "https://pan.quark.cn/s/0cd472a9c912", category: "动漫", source: "夸克网盘", mangaUrl: "https://pan.quark.cn/s/521edcada91b", mangaTitle: "漫画" },
  { title: "弹丸论破", url: "https://pan.quark.cn/s/8fdb177e3cbd", category: "动漫", source: "夸克网盘" },
  { title: "弹珠汽水瓶里的千岁同学", url: "https://pan.quark.cn/s/e9571ca020a3", category: "动漫", source: "夸克网盘" },
  { title: "当前、正被打扰中！", url: "https://pan.quark.cn/s/3018acc91da0", category: "动漫", source: "夸克网盘" },
  { title: "当我转生获得空间系统，决定把它填满垃圾", url: "https://pan.quark.cn/s/cc2029476afe", category: "动漫", source: "夸克网盘" },
  { title: "彻夜之歌", url: "https://pan.quark.cn/s/5e53afd021c1", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "怪人的沙拉碗", url: "https://pan.quark.cn/s/9438516d733b", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "怪兽8号", url: "https://pan.quark.cn/s/e111757fb661", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "总之就是非常可爱", url: "https://pan.quark.cn/s/3165bb01b1a4", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "恋爱无法用双子除尽", url: "https://pan.quark.cn/s/b356a6e0aecd", category: "动漫", source: "夸克网盘", mangaUrl: "https://pan.quark.cn/s/2992117afe1b", mangaTitle: "漫画" },
  { title: "恋爱要在征服世界后", url: "https://pan.quark.cn/s/f32947526a5b", category: "动漫", source: "夸克网盘" },
  { title: "悲喜渔生", url: "https://pan.quark.cn/s/ca1502f6a1d5", category: "动漫", source: "夸克网盘" },
  { title: "惊爆游戏", url: "https://pan.quark.cn/s/c2e46fd2581d", category: "动漫", source: "夸克网盘" },
  { title: "慎重勇者 这个勇者明明超强却过分慎重", url: "https://pan.quark.cn/s/87d35ebed50d", category: "动漫", source: "夸克网盘" },
  { title: "我们无法一起学习／我们真的学不来", url: "https://pan.quark.cn/s/000684ca0aeb", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "我和班上最讨厌的女生结婚了。", url: "https://pan.quark.cn/s/ea10817964c9", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "我怎么可能成为你的恋人，不行不行！(※不是不可能！？)", url: "https://pan.quark.cn/s/03f5e1daf77b", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "我推的孩子 番剧 漫画 真人版", url: "https://pan.quark.cn/s/5dddd264c8a1", category: "动漫", source: "夸克网盘", note: "附漫画 真人版" },
  { title: "我独自升级", url: "https://pan.quark.cn/s/705306246209", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "我的幸福婚姻", url: "https://pan.quark.cn/s/e88be420e123", category: "动漫", source: "夸克网盘" },
  { title: "我的青春恋爱物语果然有问题。", url: "https://pan.quark.cn/s/3b1af6a903df", category: "动漫", source: "夸克网盘", note: "附小说 漫画" },
  { title: "战队大失格", url: "https://pan.quark.cn/s/369e8ff53c1d", category: "动漫", source: "夸克网盘" },
  { title: "战队红战士在异世界当冒险者", url: "https://pan.quark.cn/s/e3e164b557ba", category: "动漫", source: "夸克网盘" },
  { title: "打了300年的史莱姆，不知不觉就练到了满级", url: "https://pan.quark.cn/s/87589d7c0a4e", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "打工仔的拷问日常", url: "https://pan.quark.cn/s/e45cb009ed88", category: "动漫", source: "夸克网盘" },
  { title: "排球少年", url: "https://pan.quark.cn/s/c9c7b7430217", category: "动漫", source: "夸克网盘" },
  { title: "推理要在晚餐后", url: "https://pan.quark.cn/s/3845d955179d", category: "动漫", source: "夸克网盘", note: "小说 真人版 电影" },
  { title: "搞笑漫画日和", url: "https://pan.quark.cn/s/5555f3c22338", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "摇曳露营△", url: "https://pan.quark.cn/s/ed7190cf4c77", category: "动漫", source: "夸克网盘" },
  { title: "摇滚是淑女的爱好", url: "https://pan.quark.cn/s/307d43b876ff", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "摩绪 MAO", url: "https://pan.quark.cn/s/6273d9fa1736", category: "动漫", source: "夸克网盘" },
  { title: "擅长捉弄的高木同学", url: "https://pan.quark.cn/s/a997cca8545b", category: "动漫", source: "夸克网盘", note: "附剧场版 真人版", mangaUrl: "https://link3.cc/n0range", mangaTitle: "失效、缺档请留言" },
  { title: "擅长逃跑的殿下／少主溜的快", url: "https://pan.quark.cn/s/1ed47c44af46", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "文豪野犬", url: "https://pan.quark.cn/s/c0b6eff67743", category: "动漫", source: "夸克网盘" },
  { title: "斩·赤红之瞳!", url: "https://pan.quark.cn/s/641fa5b0c973", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "新海诚16部合集", url: "https://pan.quark.cn/s/fb059b06bfc8", category: "动漫", source: "夸克网盘", note: "铃芽之旅 你的名字 天气之子" },
  { title: "无职｜转生～", url: "https://pan.quark.cn/s/551527a2fcf5", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "无能的奈奈／无能力者娜娜", url: "https://pan.quark.cn/s/9b9fc71397ab", category: "动漫", source: "夸克网盘" },
  { title: "日常 Nichijou", url: "https://pan.quark.cn/s/c5192756b032", category: "动漫", source: "夸克网盘" },
  { title: "时光流逝，饭菜依旧美味", url: "https://pan.quark.cn/s/81fa588b49f9", category: "动漫", source: "夸克网盘" },
  { title: "明天，美食广场见。", url: "https://pan.quark.cn/s/af16b861841e", category: "动漫", source: "夸克网盘" },
  { title: "明日酱的水手服", url: "https://pan.quark.cn/s/f0cc947a6202", category: "动漫", source: "夸克网盘" },
  { title: "春宵苦短，少女前进吧！", url: "https://pan.quark.cn/s/913262fc42be", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "普通攻击是全体攻击而且能二次攻击的妈妈你喜欢吗？", url: "https://pan.quark.cn/s/03ba430fd327", category: "动漫", source: "夸克网盘" },
  { title: "暗杀教室", url: "https://pan.quark.cn/s/7fd4439d8d5d", category: "动漫", source: "夸克网盘" },
  { title: "更衣人偶坠入爱河／恋上换装娃娃", url: "https://pan.quark.cn/s/02693747cece", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "最后可以再拜托您一件事吗？", url: "https://pan.quark.cn/s/9def4cf3be52", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "最近，妹妹的样子有点怪", url: "https://pan.quark.cn/s/7ba5a2348869", category: "动漫", source: "夸克网盘" },
  { title: "朋友的妹妹只喜欢烦我", url: "https://pan.quark.cn/s/a6278a89edd4", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "木头风纪委员和迷你裙JK的故事", url: "https://pan.quark.cn/s/096517f26c71", category: "动漫", source: "夸克网盘" },
  { title: "未来日记", url: "https://pan.quark.cn/s/68d6f4cd5dfc", category: "动漫", source: "夸克网盘" },
  { title: "未闻花名／我们仍未知道那天所看见的花的名字。", url: "https://pan.quark.cn/s/02b6a0115da1", category: "动漫", source: "夸克网盘", note: "附漫画 · 续集也会在原链接继续更新" },
  { title: "末日时在做什么？有没有空？可以来拯救吗？", url: "https://pan.quark.cn/s/fda54e8060e9", category: "动漫", source: "夸克网盘" },
  { title: "朱音落語", url: "https://pan.quark.cn/s/7a1a6b7887fa", category: "动漫", source: "夸克网盘" },
  { title: "机动战士高达 GQuuuuuuX", url: "https://pan.quark.cn/s/48a2bd41ada5", category: "动漫", source: "夸克网盘" },
  { title: "机巧少女不会受伤", url: "https://pan.quark.cn/s/5c6532e5ad78", category: "动漫", source: "夸克网盘" },
  { title: "杜鹃的婚约", url: "https://pan.quark.cn/s/4618193cad6a", category: "动漫", source: "夸克网盘" },
  { title: "来自深渊", url: "https://pan.quark.cn/s/9d97703d431b", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "枪神 Trigun", url: "https://pan.quark.cn/s/9078bea6a24b", category: "动漫", source: "夸克网盘" },
  { title: "某科学的一方通行", url: "https://pan.quark.cn/s/526d1c84f091", category: "动漫", source: "夸克网盘" },
  { title: "某科学的超电.磁炮", url: "https://pan.quark.cn/s/4d027e3991da", category: "动漫", source: "夸克网盘" },
  { title: "楠木邸的神明庭院", url: "https://pan.quark.cn/s/14df5cde0365", category: "动漫", source: "夸克网盘" },
  { title: "樱兰高校男公关部", url: "https://pan.quark.cn/s/9bbd44247944", category: "动漫", source: "夸克网盘" },
  { title: "欢迎光临流放者食堂！", url: "https://pan.quark.cn/s/810eb5a3e393", category: "动漫", source: "夸克网盘" },
  { title: "欢迎来到笑容不断的职场／这里是充满笑容的职场", url: "https://pan.quark.cn/s/32485ce09532", category: "动漫", source: "夸克网盘" },
  { title: "死亡笔记", url: "https://pan.quark.cn/s/e50d3df467ab", category: "动漫", source: "夸克网盘", note: "附漫画 真人版" },
  { title: "死神少爷与黑女仆", url: "https://pan.quark.cn/s/96c47f26fffc", category: "动漫", source: "夸克网盘" },
  { title: "水属性的魔法师", url: "https://pan.quark.cn/s/b446930b64ab", category: "动漫", source: "夸克网盘" },
  { title: "没有辣妹会对阿宅温柔", url: "https://pan.quark.cn/s/8487af7acafd", category: "动漫", source: "夸克网盘" },
  { title: "派对浪客诸葛孔明", url: "https://pan.quark.cn/s/c5127f21e6df", category: "动漫", source: "夸克网盘" },
  { title: "测不准的阿波连同学", url: "https://pan.quark.cn/s/a085392e5fc2", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "淡岛百景", url: "https://pan.quark.cn/s/480f51a6e369", category: "动漫", source: "夸克网盘" },
  { title: "深夜PUNCH／深夜冲击／深夜重拳", url: "https://pan.quark.cn/s/6c71a3bc171c", category: "动漫", source: "夸克网盘" },
  { title: "渡君的XX即将崩坏", url: "https://pan.quark.cn/s/a3f92f8c0980", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "游戏人生", url: "https://pan.quark.cn/s/822fce517432", category: "动漫", source: "夸克网盘" },
  { title: "火影忍者", url: "https://pan.quark.cn/s/1a87fde602ca", category: "动漫", source: "夸克网盘", note: "全集+剧场+漫画" },
  { title: "灵能百分百", url: "https://pan.quark.cn/s/ed948648a823", category: "动漫", source: "夸克网盘" },
  { title: "炎炎消防队", url: "https://pan.quark.cn/s/58323bd24638", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "熊熊勇闯异世界", url: "https://pan.quark.cn/s/fff9b8aebb67", category: "动漫", source: "夸克网盘" },
  { title: "熏香花朵凛然绽放", url: "https://pan.quark.cn/s/3931c1f581f4", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "爷爷奶奶返老还童／老夫老妻重返青春", url: "https://pan.quark.cn/s/cdd0943009bb", category: "动漫", source: "夸克网盘" },
  { title: "物语系列", url: "https://pan.quark.cn/s/3b163327dcbb", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "犬夜叉", url: "https://pan.quark.cn/s/66f5b08a1c20", category: "动漫", source: "夸克网盘" },
  { title: "狂赌之渊", url: "https://pan.quark.cn/s/fad502987770", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "猪肝记得煮熟再吃 ／猪肝倒是热热再吃啊", url: "https://pan.quark.cn/s/b418156f5f50", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "猫和老鼠1-14季+15部大电影 +50周年珍藏版", url: "https://pan.quark.cn/s/6f9421e52369", category: "动漫", source: "夸克网盘" },
  { title: "猫娘乐园Nekopara", url: "https://pan.quark.cn/s/a52960324d65", category: "动漫", source: "夸克网盘" },
  { title: "猫眼三姐妹（2025）", url: "https://pan.quark.cn/s/75b02a25aef7", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "玉子市场", url: "https://pan.quark.cn/s/457c50afbe5d", category: "动漫", source: "夸克网盘" },
  { title: "王者天下", url: "https://pan.quark.cn/s/c32ba527383d", category: "动漫", source: "夸克网盘" },
  { title: "现在多闻君是哪一面！？", url: "https://pan.quark.cn/s/db2d4a2263b2", category: "动漫", source: "夸克网盘" },
  { title: "理科生坠入情网故尝试证明", url: "https://pan.quark.cn/s/0e219dbb163c", category: "动漫", source: "夸克网盘" },
  { title: "琉璃的宝石", url: "https://pan.quark.cn/s/178788d2c960", category: "动漫", source: "夸克网盘" },
  { title: "甘城光辉游乐园", url: "https://pan.quark.cn/s/032c949c0bf1", category: "动漫", source: "夸克网盘" },
  { title: "甲铁城的卡巴内利", url: "https://pan.quark.cn/s/978a09a2a7cb", category: "动漫", source: "夸克网盘" },
  { title: "电锯人 - 剧场版：蕾塞篇 (2025)", url: "https://pan.quark.cn/s/9360ad37fd39", category: "动漫", source: "夸克网盘" },
  { title: "男女之间的友情存在吗？（不，不存在!!）", url: "https://pan.quark.cn/s/a1868131a413", category: "动漫", source: "夸克网盘" },
  { title: "異獸魔都", url: "https://pan.quark.cn/s/9a9bb8c3db45", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "白色相簿", url: "https://pan.quark.cn/s/e54e0c068165", category: "动漫", source: "夸克网盘" },
  { title: "百变的七仓同学／疑.似.后宫", url: "https://pan.quark.cn/s/6c7296e48119", category: "动漫", source: "夸克网盘" },
  { title: "百鬼夜行抄", url: "https://pan.quark.cn/s/8a10bb2114cf", category: "动漫", source: "夸克网盘" },
  { title: "皎洁迎宵之月", url: "https://pan.quark.cn/s/2ea69c039204", category: "动漫", source: "夸克网盘" },
  { title: "相反的你和我", url: "https://pan.quark.cn/s/370c09a62663", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "盾之勇者成名录", url: "https://pan.quark.cn/s/c2c0e7ee0836", category: "动漫", source: "夸克网盘" },
  { title: "看得见的女孩 阴阳眼见子", url: "https://pan.quark.cn/s/b496c5f953d4", category: "动漫", source: "夸克网盘" },
  { title: "瞬间治疗却被视为无用而被流放的天才治疗师，以暗黑治疗师的身份幸福地生活着", url: "https://pan.quark.cn/s/97969ebe3e01", category: "动漫", source: "夸克网盘" },
  { title: "矢野同学观察日记／矢野同学的普通日常", url: "https://pan.quark.cn/s/cc5c86c2beb3", category: "动漫", source: "夸克网盘" },
  { title: "石纪元", url: "https://pan.quark.cn/s/9fb9e1915068", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "碧蓝之海", url: "https://pan.quark.cn/s/848ac1006e3e", category: "动漫", source: "夸克网盘", note: "附真人版 漫画" },
  { title: "神之水滴／神之雫", url: "https://pan.quark.cn/s/e8ebc9bbec58", category: "动漫", source: "夸克网盘" },
  { title: "秘密内幕～女警的反击", url: "https://pan.quark.cn/s/9245010302c3", category: "动漫", source: "夸克网盘" },
  { title: "租借女友", url: "https://pan.quark.cn/s/39aebbe28726", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "章鱼噼的原罪", url: "https://pan.quark.cn/s/9f72f5c648e5", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "笨女孩", url: "https://pan.quark.cn/s/b56d02d71e47", category: "动漫", source: "夸克网盘" },
  { title: "紫云寺家的兄弟姐妹", url: "https://pan.quark.cn/s/1d0a2c4f7776", category: "动漫", source: "夸克网盘" },
  { title: "紫罗兰永恒花园", url: "https://pan.quark.cn/s/110e7c9c345e", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "约会大作战", url: "https://pan.quark.cn/s/0203bb44e583", category: "动漫", source: "夸克网盘" },
  { title: "约定的梦幻岛", url: "https://pan.quark.cn/s/be69e750179b", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "线上游戏的老婆不可能是女生？", url: "https://pan.quark.cn/s/d6d2f32fff96", category: "动漫", source: "夸克网盘" },
  { title: "终将成为你", url: "https://pan.quark.cn/s/50a5e08b69a3", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "经验丰富的你和经验为零的我交往的故事／位于恋爱光谱极端的我们", url: "https://pan.quark.cn/s/bd30d2da05df", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "结城友奈是勇者", url: "https://pan.quark.cn/s/c8313ec32a3e", category: "动漫", source: "夸克网盘" },
  { title: "绝对双刃", url: "https://pan.quark.cn/s/c095a0c6c335", category: "动漫", source: "夸克网盘" },
  { title: "绯弹的亚里亚", url: "https://pan.quark.cn/s/3d264322ad2c", category: "动漫", source: "夸克网盘" },
  { title: "罪恶王冠", url: "https://pan.quark.cn/s/7d122080620f", category: "动漫", source: "夸克网盘" },
  { title: "自称恶役大小姐的婚约者观察记录", url: "https://pan.quark.cn/s/75442092796e", category: "动漫", source: "夸克网盘" },
  { title: "致不灭的你", url: "https://pan.quark.cn/s/00fb2e945017", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "花样少年少女", url: "https://pan.quark.cn/s/1f93f3d168ce", category: "动漫", source: "夸克网盘" },
  { title: "苍翼默示录 ALTER MEMORY", url: "https://pan.quark.cn/s/b0e8c2e8e652", category: "动漫", source: "夸克网盘" },
  { title: "草莓百分百", url: "https://pan.quark.cn/s/51047a08b28e", category: "动漫", source: "夸克网盘" },
  { title: "荒川爆笑团", url: "https://pan.quark.cn/s/a54bb8ec5c2f", category: "动漫", source: "夸克网盘" },
  { title: "药屋少女的呢喃", url: "https://pan.quark.cn/s/82ed2ba68703", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "莱莎的炼金工房 ~常暗女王与秘密藏身处~", url: "https://pan.quark.cn/s/6854659603ac", category: "动漫", source: "夸克网盘" },
  { title: "萝球社！", url: "https://pan.quark.cn/s/04db3ff6aec9", category: "动漫", source: "夸克网盘", note: "附漫画 小说" },
  { title: "落第骑士英雄谭", url: "https://pan.quark.cn/s/9b775202018b", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "蓝箱／青之箱", url: "https://pan.quark.cn/s/7fdd63e0039b", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "蓝色监狱", url: "https://pan.quark.cn/s/19994041c2d0", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "蓦然回首 (Look Back)", url: "https://pan.quark.cn/s/77d46a5e67d7", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "藤本树17-26", url: "https://pan.quark.cn/s/d5a1c514c771", category: "动漫", source: "夸克网盘" },
  { title: "虽然是公会的前台小姐，因为讨厌加班，所以打算自己讨伐boss", url: "https://pan.quark.cn/s/66127a539c22", category: "动漫", source: "夸克网盘" },
  { title: "街角魔族", url: "https://pan.quark.cn/s/14494cc946a3", category: "动漫", source: "夸克网盘" },
  { title: "被邻国王子溺爱的反派女主", url: "https://pan.quark.cn/s/3a7bb9220bb7", category: "动漫", source: "夸克网盘" },
  { title: "见面5秒开始战斗", url: "https://pan.quark.cn/s/f512a44a783e", category: "动漫", source: "夸克网盘" },
  { title: "请问您今天要来点兔子吗？", url: "https://pan.quark.cn/s/353dfbff0a03", category: "动漫", source: "夸克网盘" },
  { title: "败犬女主太多了！", url: "https://pan.quark.cn/s/a9a2f0884f55", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "贵族转生 ～得天眷顾一出生就获得最强力量～", url: "https://pan.quark.cn/s/5ff511dedb7e", category: "动漫", source: "夸克网盘" },
  { title: "赌博默示录", url: "https://pan.quark.cn/s/a4013f31ecac", category: "动漫", source: "夸克网盘" },
  { title: "赛博朋克：边缘行者", url: "https://pan.quark.cn/s/c71ffb8d6073", category: "动漫", source: "夸克网盘" },
  { title: "赛马娘", url: "https://pan.quark.cn/s/ca56c5f1fa2b", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "赛马娘 芦毛灰姑娘", url: "https://pan.quark.cn/s/a81221181c3b", category: "动漫", source: "夸克网盘" },
  { title: "超时空辉夜姬！", url: "https://pan.quark.cn/s/7e05dda92d24", category: "动漫", source: "夸克网盘" },
  { title: "超自然武装当哒当／胆大党", url: "https://pan.quark.cn/s/540289ab1f9b", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "超超超超超喜欢你的100个女朋友", url: "https://pan.quark.cn/s/df069933da30", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "跃动青春", url: "https://pan.quark.cn/s/ef5d53632c7f", category: "动漫", source: "夸克网盘", note: "带漫画" },
  { title: "路人女主的养成方法", url: "https://pan.quark.cn/s/89befac1be31", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "身为暗杀者的我明显比勇者还强", url: "https://pan.quark.cn/s/5d09f840702e", category: "动漫", source: "夸克网盘" },
  { title: "身为魔族的我想向勇者小队的可爱女孩告白。", url: "https://pan.quark.cn/s/a6fe00a2c6b1", category: "动漫", source: "夸克网盘" },
  { title: "身为魔王的我娶了奴隶精灵为妻，该如何表白我的爱？", url: "https://pan.quark.cn/s/27cfdde64e49", category: "动漫", source: "夸克网盘", note: "附漫画 小说" },
  { title: "躲在超市后门抽烟的两人", url: "https://pan.quark.cn/s/f699b40d2882", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "輪迴的花瓣/轮回的花瓣", url: "https://pan.quark.cn/s/e3559124f16e", category: "动漫", source: "夸克网盘" },
  { title: "转生七王子的魔法全解／转生为第七王子，随心所欲的魔法学习之路", url: "https://pan.quark.cn/s/eb144cfb3691", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "转生就是剑／转生成为魔剑", url: "https://pan.quark.cn/s/904985595304", category: "动漫", source: "夸克网盘" },
  { title: "转生成为了只有乙女游戏破灭Flag的邪恶大小姐", url: "https://pan.quark.cn/s/249a25010c9a", category: "动漫", source: "夸克网盘" },
  { title: "转生成自动贩卖机的我今天也在迷宫徘徊", url: "https://pan.quark.cn/s/978f7f702db1", category: "动漫", source: "夸克网盘" },
  { title: "转生成蜘蛛又怎样！", url: "https://pan.quark.cn/s/2a2837b94cc5", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "辉夜大小姐想让我告白～天才们的恋爱头脑战～", url: "https://pan.quark.cn/s/44f5774a342b", category: "动漫", source: "夸克网盘" },
  { title: "达尔文事变", url: "https://pan.quark.cn/s/39f81b98e30c", category: "动漫", source: "夸克网盘" },
  { title: "这公司有我喜欢的人 附漫画", url: "https://pan.quark.cn/s/3b4cb6cbacdb", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "进击的巨人", url: "https://pan.quark.cn/s/a17b457e31c9", category: "动漫", source: "夸克网盘" },
  { title: "迦楠大人的白给是恶魔级", url: "https://pan.quark.cn/s/0ecdaff48681", category: "动漫", source: "夸克网盘" },
  { title: "迪士尼扭曲仙境", url: "https://pan.quark.cn/s/764d3c2872f3", category: "动漫", source: "夸克网盘" },
  { title: "透明男与人类女～不久成为夫妇的二人～", url: "https://pan.quark.cn/s/c8059932b38d", category: "动漫", source: "夸克网盘" },
  { title: "通灵王 系列合集（FLOWERS+旧版+新版）", url: "https://pan.quark.cn/s/c76f39bc9a0f", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "重启咲良田", url: "https://pan.quark.cn/s/ad65da159066", category: "动漫", source: "夸克网盘" },
  { title: "金牌得主／舞冰的祈愿", url: "https://pan.quark.cn/s/e3c6f588926a", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "钢之炼金术师", url: "https://pan.quark.cn/s/2dabd0a7d0d1", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "钻石王牌", url: "https://pan.quark.cn/s/237256ef8560", category: "动漫", source: "夸克网盘" },
  { title: "银魂", url: "https://pan.quark.cn/s/8ebf20593399", category: "动漫", source: "夸克网盘", note: "附漫画 真人版" },
  { title: "间谍教室", url: "https://pan.quark.cn/s/9e9126e20bd8", category: "动漫", source: "夸克网盘" },
  { title: "间谍过家家", url: "https://pan.quark.cn/s/8b48b46632f7", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "防风铃／防风少年", url: "https://pan.quark.cn/s/f848d305e396", category: "动漫", source: "夸克网盘" },
  { title: "阳光马达棒球场！", url: "https://pan.quark.cn/s/b7ab8bccc19e", category: "动漫", source: "夸克网盘" },
  { title: "雀魂", url: "https://pan.quark.cn/s/f56ac2320323", category: "动漫", source: "夸克网盘" },
  { title: "雨天遇见狸／和雨和你", url: "https://pan.quark.cn/s/fd6afa7442f7", category: "动漫", source: "夸克网盘" },
  { title: "雾尾粉丝后援会", url: "https://pan.quark.cn/s/954791e1df5b", category: "动漫", source: "夸克网盘" },
  { title: "青春猪头少年系列", url: "https://pan.quark.cn/s/2c2bd13c814f", category: "动漫", source: "夸克网盘", note: "附小说 · 兔女郎 红书包 怀梦少女 圣诞服" },
  { title: "非人学生与厌世教师", url: "https://pan.quark.cn/s/897ac6ef3f40", category: "动漫", source: "夸克网盘" },
  { title: "靠死亡遊戲混饭吃／以死亡遊戲為生", url: "https://pan.quark.cn/s/3490ebcf0431", category: "动漫", source: "夸克网盘" },
  { title: "高校奇面组", url: "https://pan.quark.cn/s/61c69c28464a", category: "动漫", source: "夸克网盘" },
  { title: "鬼泣 Devil May Cry (2025)", url: "https://pan.quark.cn/s/7e9ec1248b2e", category: "动漫", source: "夸克网盘" },
  { title: "鬼灭之刃", url: "https://pan.quark.cn/s/d41906a069c8", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "魔.法.禁.书.目.录", url: "https://pan.quark.cn/s/6683a2d41b45", category: "动漫", source: "夸克网盘" },
  { title: "魔兵传奇", url: "https://pan.quark.cn/s/7fbc219a4cb5", category: "动漫", source: "夸克网盘" },
  { title: "魔卡少女樱", url: "https://pan.quark.cn/s/779b2961c518", category: "动漫", source: "夸克网盘" },
  { title: "魔女与使魔／魔女守护者", url: "https://pan.quark.cn/s/33aa4e7d02db", category: "动漫", source: "夸克网盘" },
  { title: "魔女之旅", url: "https://pan.quark.cn/s/3efb7b75ea7e", category: "动漫", source: "夸克网盘", note: "附小说" },
  { title: "魔法使光之美少女！！～MIRAI DAYS～", url: "https://pan.quark.cn/s/671a98bc8b0c", category: "动漫", source: "夸克网盘" },
  { title: "魔法少女与恶曾是敌人。", url: "https://pan.quark.cn/s/3ca3f05ebd32", category: "动漫", source: "夸克网盘" },
  { title: "魔法少女奈叶", url: "https://pan.quark.cn/s/fa9429ce0926", category: "动漫", source: "夸克网盘" },
  { title: "魔法少女小圆", url: "https://pan.quark.cn/s/fafda2397883", category: "动漫", source: "夸克网盘" },
  { title: "魔法科高校的劣等生", url: "https://pan.quark.cn/s/eacece6f1d38", category: "动漫", source: "夸克网盘", note: "带小说" },
  { title: "魔法纪录 魔法少女小圆外传", url: "https://pan.quark.cn/s/de22021af429", category: "动漫", source: "夸克网盘" },
  { title: "魔王的女儿太温柔了！！", url: "https://pan.quark.cn/s/6541d7fd82b4", category: "动漫", source: "夸克网盘" },
  { title: "鸭乃桥论的禁忌推理", url: "https://pan.quark.cn/s/ea02bd3c4f06", category: "动漫", source: "夸克网盘" },
  { title: "鹿乃子乃子虎视眈眈", url: "https://pan.quark.cn/s/5bec135473f6", category: "动漫", source: "夸克网盘" },
  { title: "齐木楠雄的灾难", url: "https://pan.quark.cn/s/b13f1c0f0f4c", category: "动漫", source: "夸克网盘", note: "附漫画" },
  { title: "龙王的工作", url: "https://pan.quark.cn/s/52ce78e4a3c9", category: "动漫", source: "夸克网盘", note: "附小说" },

  // ===== 学习资料 (140) =====
  { title: "2024年二级建造师全网最全电子版资料", url: "https://pan.quark.cn/s/b5390c103cfc", category: "学习资料", source: "夸克网盘" },
  { title: "2025《毕业论文、毕业答辩》精选资料汇总", url: "https://pan.quark.cn/s/78837394da00", category: "学习资料", source: "夸克网盘" },
  { title: "24年中级经济师网课【基础】", url: "https://pan.quark.cn/s/8d6f08c78475", category: "学习资料", source: "夸克网盘" },
  { title: "24年中经【财税】", url: "https://pan.quark.cn/s/abee511888f2", category: "学习资料", source: "夸克网盘" },
  { title: "少儿编程课课程整理", url: "https://pan.quark.cn/s/64e357334197", category: "学习资料", source: "夸克网盘" },
  // --- 各类书籍 ---
  { title: "《2024年豆瓣高分TOP100书单电子书》合集", url: "https://pan.quark.cn/s/e5f8db631aa2", category: "学习资料", source: "夸克网盘", section: "各类书籍" },
  { title: "四大名著-小说原著", url: "https://pan.quark.cn/s/df0c9f1f741d", category: "学习资料", source: "夸克网盘", section: "各类书籍" },
  { title: "脑洞w烧脑x", url: "https://pan.quark.cn/s/0fbead8d6705", category: "学习资料", source: "夸克网盘", section: "各类书籍" },
  // --- 各类教材 ---
  { title: "初中教材", url: "https://pan.baidu.com/s/1I1DQ52laX9gJaGlAGQMMMQ?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "初中（五•四学制）教材", url: "https://pan.baidu.com/s/1T0SqBY_rp1a8tpd2zr2jSQ?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "大学教材", url: "https://pan.baidu.com/s/1owUhh6JZJfMUG6BMEfqihA?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "小学教材", url: "https://pan.baidu.com/s/1O3s6vnuIwrHgEZMqwnd_qQ?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "小学（五•四学制）教材", url: "https://pan.baidu.com/s/14tNMApZb801KRNPiSfLcTA?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "广东高校联盟学位英语教材、历年真题", url: "https://pan.baidu.com/s/1WUfZhcxl7Re9DP75YMFWtw?pwd=48ue", category: "学习资料", source: "百度网盘", code: "48ue", section: "各类教材" },
  { title: "数学习题", url: "https://pan.baidu.com/s/1qZLcen9V7p9WDYKW5c5ahg?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  { title: "高中教材", url: "https://pan.baidu.com/s/1HqXc5Oc8Fw5Tgv39QRP77Q?pwd=ewwg", category: "学习资料", source: "百度网盘", code: "ewwg", section: "各类教材" },
  // --- 推理小说 ---
  { title: "【日】东野圭吾（作品集）", url: "https://pan.baidu.com/s/17f-ViSvKt8ssXtknDrHCgA?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", note: "社会派推理，入门必看", section: "推理小说" },
  { title: "【日】伊坂幸太郎（作品集）", url: "https://pan.baidu.com/s/12mDN7Yz9teRtX7JNLQZbDQ?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", section: "推理小说" },
  { title: "【日】森村诚一 典藏集（套装共69本）", url: "https://pan.baidu.com/s/1GvNwRcQudQLcn-e9sacPKg?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", section: "推理小说" },
  { title: "【日】绫辻行人（作品集）", url: "https://pan.baidu.com/s/151B3GUhIrRLW4n9waK1WnQ?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", note: "馆系列", section: "推理小说" },
  { title: "【美】埃勒里·奎因（作品集）", url: "https://pan.baidu.com/s/1xNsXMIYrGmAaQuJd36fiaQ?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", section: "推理小说" },
  { title: "【美】雷蒙德·钱德勒作品（套装共10册）", url: "https://pan.baidu.com/s/1I1fW4HCB9thvCRxOSoMw5A?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", section: "推理小说" },
  { title: "【英】约瑟芬.铁伊推理全集（全8册）", url: "https://pan.baidu.com/s/1pIrEFk0KGNw439wzO5_2Cw?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", note: "出品皆精品", section: "推理小说" },
  { title: "【英】阿加莎・克里斯蒂（作品集）", url: "https://pan.baidu.com/s/1cmboxfKEtnV4H2vc0ADfMQ?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", note: "阿婆系列", section: "推理小说" },
  { title: "紫金陈书单", url: "https://pan.baidu.com/s/18Q-RI1TCXN4lULKk3zktsw?pwd=n6y2", category: "学习资料", source: "百度网盘", code: "n6y2", note: "前期作品有东野圭吾的味道，很推荐长夜难明，智商系列也不错", section: "推理小说" },
  // --- 豆瓣TOP100电子书 ---
  { title: "100浪潮之巅（第四版）", url: "https://pan.quark.cn/s/e9fc149d92f4", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "10三国演义（精装）（古典文库）", url: "https://pan.quark.cn/s/faa6ac6fb568", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "11福尔摩斯探案全集（插图珍藏版·全7册）", url: "https://pan.quark.cn/s/8581698e3fc1", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "12白夜行", url: "https://pan.quark.cn/s/67d3ba42b4f0", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "13小王子（上海译文版）", url: "https://pan.quark.cn/s/7362ad703a98", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "14安徒生童话全集·全12册", url: "https://pan.quark.cn/s/95ccea72a6b5", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "15天龙八部（世纪新修版）", url: "https://pan.quark.cn/s/70481accfb01", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "16撒哈拉的故事", url: "https://pan.quark.cn/s/6df480b532ea", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "17呐喊：百年纪念版", url: "https://pan.quark.cn/s/dd8fa088969e", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "19悉达多 -赫尔曼·黑塞", url: "https://pan.quark.cn/s/4aae4f59e50d", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "1红楼梦", url: "https://pan.quark.cn/s/7c4122cb23f4", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "20杀死一只知更鸟", url: "https://pan.quark.cn/s/187c13a03a5c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "21失踪的孩子", url: "https://pan.quark.cn/s/dc7cffd033fd", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "22明朝那些事儿（全套9册图文增补版）", url: "https://pan.quark.cn/s/33043b6c1299", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "23新名字的故事", url: "https://pan.quark.cn/s/12a9ac37cb77", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "24野草", url: "https://pan.quark.cn/s/af89d9286798", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "25沉默的大多数", url: "https://pan.quark.cn/s/bf3e790c6ac2", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "26中国历代政治得失", url: "https://pan.quark.cn/s/eee4afd57ca6", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "27局外人（上海译文版）", url: "https://pan.quark.cn/s/28bece9d7331", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "28白鹿原(20周年纪念版)_陈忠实", url: "https://pan.quark.cn/s/8ea51cce3e93", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "29卡拉马佐夫兄弟", url: "https://pan.quark.cn/s/42dccaecf32b", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "2活着", url: "https://pan.quark.cn/s/8ac586440a95", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "30乡土中国（修订本）", url: "https://pan.quark.cn/s/33a4814dbe03", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "31人类简史", url: "https://pan.quark.cn/s/a92ed863381c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "32平凡的世界（全三册）", url: "https://pan.quark.cn/s/e8f5aba3a672", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "33鲁迅自编文集(呐喊_彷徨_朝花夕拾_故事新编)(套装共4册)", url: "https://pan.quark.cn/s/90ec8d695852", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "34围城", url: "https://pan.quark.cn/s/4a83da1a0c08", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "35罗杰疑案", url: "https://pan.quark.cn/s/65565b5703e2", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "36笑傲江湖", url: "https://pan.quark.cn/s/ce28b3ec8f35", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "37余华长篇小说：在细雨中呼喊_兄弟_许三观卖血记_活着（套装共4册）", url: "https://pan.quark.cn/s/4d63ad08a234", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "38我与地坛", url: "https://pan.quark.cn/s/38993c250021", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "39献给阿尔吉侬的花束", url: "https://pan.quark.cn/s/37c767cdc16f", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "3哈利波特完整系列", url: "https://pan.quark.cn/s/fe2471b320f6", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "4.1984-乔治.奥威尔", url: "https://pan.quark.cn/s/5dca32fccd37", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "40东方快车谋杀案（精装纪念版）", url: "https://pan.quark.cn/s/d7d1cfd108e8", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "41肖申克的救赎", url: "https://pan.quark.cn/s/70d3672481af", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "43基督山伯爵", url: "https://pan.quark.cn/s/867a571720d8", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "44城南旧事（绘图本）", url: "https://pan.quark.cn/s/355f6cd2a1e4", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "45霍乱时期的爱情", url: "https://pan.quark.cn/s/1745a2ea44f8", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "46故事新编", url: "https://pan.quark.cn/s/9ed6856f3259", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "47艺术的故事(共12册)", url: "https://pan.quark.cn/s/1b929045f9ab", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "48朝花夕拾", url: "https://pan.quark.cn/s/621bb57bedc5", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "49万历十五年（经典版）", url: "https://pan.quark.cn/s/c73643c84d84", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "50月亮和六便士", url: "https://pan.quark.cn/s/6be31ea8fe18", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "51厌女（增订本）", url: "https://pan.quark.cn/s/99d9e6f1b9b9", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "52秋园", url: "https://pan.quark.cn/s/3dc11ff12946", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "53置身事内", url: "https://pan.quark.cn/s/5ded111a8549", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "54射雕英雄传", url: "https://pan.quark.cn/s/c20a6b5a73f0", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "55追风筝的人", url: "https://pan.quark.cn/s/1caf275a07c3", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "56寻路中国", url: "https://pan.quark.cn/s/6b25a744a546", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "57刀锋（上海译文版）", url: "https://pan.quark.cn/s/03491c4cbee2", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "58树上的男爵", url: "https://pan.quark.cn/s/3c4190d107cb", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "59中国少年儿童百科全书（全四册）", url: "https://pan.quark.cn/s/957d47528617", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "5三体全集（套装共3册）", url: "https://pan.quark.cn/s/8177d0396cbc", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "60无人生还（精装纪念版）", url: "https://pan.quark.cn/s/a1bc48e4b707", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "61格林童话全集", url: "https://pan.quark.cn/s/3718038d34a6", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "62鼠疫-阿尔贝·加缪", url: "https://pan.quark.cn/s/80a489da37be", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "63西游记：校注本（套装2册）", url: "https://pan.quark.cn/s/e6fd9035eaf5", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "64嫌疑人X的献身", url: "https://pan.quark.cn/s/9bdaf9c09e34", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "65可能性的艺术", url: "https://pan.quark.cn/s/19f9f8e079a1", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "66黄金时代", url: "https://pan.quark.cn/s/1616162480ff", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "67史记全译", url: "https://pan.quark.cn/s/bba0aa187572", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "68始于极限", url: "https://pan.quark.cn/s/e70a8e778ad9", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "69傲慢与偏见（译文名著典藏）", url: "https://pan.quark.cn/s/343424d70102", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "6百年孤独（50周年纪念版）", url: "https://pan.quark.cn/s/04072441b970", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "70台北人", url: "https://pan.quark.cn/s/d5184b266253", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "71悲惨世界(全3册)", url: "https://pan.quark.cn/s/f48dcd554852", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "72诗经（全二册）--中华经典名著全本全注全译 (中华经典名著全本全注全译丛书)", url: "https://pan.quark.cn/s/377fb82196c5", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "73刘擎西方现代思想讲义", url: "https://pan.quark.cn/s/921fc90678ed", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "74孽子", url: "https://pan.quark.cn/s/feae8b015bbf", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "75阿西莫夫：永恒的终结", url: "https://pan.quark.cn/s/ec01745aa4ba", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "76太白金星有点烦-马伯庸", url: "https://pan.quark.cn/s/1fbdb23dcd2c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "77神雕侠侣", url: "https://pan.quark.cn/s/8dc083285eeb", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "78历史深处的忧虑", url: "https://pan.quark.cn/s/da6db3c04829", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "79上帝掷骰子吗？：量子物理史话：升级版", url: "https://pan.quark.cn/s/1588b411ce8b", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "7飘", url: "https://pan.quark.cn/s/2cd8281c8f2c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "80美丽新世界", url: "https://pan.quark.cn/s/4a5812a911a6", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "81一个叫欧维的男人决定去死", url: "https://pan.quark.cn/s/e31c69a66b24", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "82四世同堂（完整版）（全三册）", url: "https://pan.quark.cn/s/5a9162e7b194", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "83唐诗三百首", url: "https://pan.quark.cn/s/d0b166c299b6", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "84美的历程", url: "https://pan.quark.cn/s/8bc7f0a96b18", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "85哭泣的骆驼", url: "https://pan.quark.cn/s/b393a9b8de34", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "86灿烂千阳", url: "https://pan.quark.cn/s/6de541899490", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "87文学回忆录", url: "https://pan.quark.cn/s/30ffcbdd8024", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "88最好的告别三部曲（套装共3册）", url: "https://pan.quark.cn/s/68f331abdd23", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "89窗边的小豆豆", url: "https://pan.quark.cn/s/2acc32358c5c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "8动物农场", url: "https://pan.quark.cn/s/7a601dbeee52", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "90呼兰河传（完整版插图本）", url: "https://pan.quark.cn/s/9c8e4a30c2d5", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "91人间词话", url: "https://pan.quark.cn/s/64c36c43abd3", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "92罪与罚", url: "https://pan.quark.cn/s/42b054cba798", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "93绝叫", url: "https://pan.quark.cn/s/2d091c0db9f3", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "94冬牧场", url: "https://pan.quark.cn/s/4dcee2cd2459", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "95道德经", url: "https://pan.quark.cn/s/401eebcb1eab", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "96树王棋王孩子王", url: "https://pan.quark.cn/s/a91cfc30d40d", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "97毛泽东选集（全4卷）", url: "https://pan.quark.cn/s/fb7b0b2e9125", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "98看见", url: "https://pan.quark.cn/s/e2e8099355c8", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "99也许你该找个人聊聊", url: "https://pan.quark.cn/s/26e07053d36c", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  { title: "9房思琪的初恋乐园", url: "https://pan.quark.cn/s/77b65d531547", category: "学习资料", source: "夸克网盘", section: "豆瓣TOP100电子书" },
  // --- 安全技术书籍 ---
  { title: "ASP.NET从入门到精通第2版.pdf", url: "https://pan.quark.cn/s/03dada863ac8", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Android安全攻防权威指南.pdf", url: "https://pan.quark.cn/s/18cdf7ec3530", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Android软件安全与逆向分析.pdf", url: "https://pan.quark.cn/s/7cc04ee2876f", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "HADOOP权威指南 第3版 完整版.pdf", url: "https://pan.quark.cn/s/6ffefbc9f15e", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Java编辑思想（第四版）.pdf", url: "https://pan.quark.cn/s/400c276d3a0a", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "JavaScript权威指南(第6版)(中文版).pdf", url: "https://pan.quark.cn/s/2da5a3f59aff", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "JavaScript框架高级编程.pdf", url: "https://pan.quark.cn/s/81cb5534916d", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Metasploit渗透测试魔鬼训练营-完整版.pdf", url: "https://pan.quark.cn/s/43f933e31d30", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "PHP Web安全开发实战_.pdf", url: "https://pan.quark.cn/s/8172ff30e451", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "PHP安全之道  项目安全的架构、技术与实践.pdf", url: "https://pan.quark.cn/s/cc2120081e3f", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Python黑帽子+黑客与渗透测试编程之道.pdf", url: "https://pan.quark.cn/s/55771dcbfbeb", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Web网站漏洞扫描与渗透攻击工具揭秘.pdf", url: "https://pan.quark.cn/s/d236c6117c6c", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Web渗透技术及实战案例解析.pdf", url: "https://pan.quark.cn/s/4f0ea3168d5e", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Web渗透测试：使用Kali Linux .pdf", url: "https://pan.quark.cn/s/2d3314fa9ae6", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "Wireshark 数据包分析实战（第二版）.pdf", url: "https://pan.quark.cn/s/8fa00621a211", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "《白帽子讲Web安全》 吴翰清.pdf", url: "https://pan.quark.cn/s/3a4173aa474f", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },
  { title: "社会工程：安全体系中的人性漏洞 ([美]Christopher Hadnagy [Hadnagy, Christopher]) .pdf", url: "https://pan.quark.cn/s/b7cc5eb3f73c", category: "学习资料", source: "夸克网盘", section: "安全技术书籍" },

  // ===== 安卓软件 (10) =====
  { title: "MT管理器安卓逆向工具 MT2.18.4.apk", url: "https://pan.quark.cn/s/2734e97e6b2e", category: "安卓软件", source: "夸克网盘" },
  { title: "局域网传输工具 LocalSend.zip", url: "https://pan.quark.cn/s/17fdace41f15", category: "安卓软件", source: "夸克网盘", note: "支持安卓、windows、linux、maxos" },
  { title: "应用架构分析工具LibChecker.zip", url: "https://pan.quark.cn/s/43482848e622", category: "安卓软件", source: "夸克网盘" },
  { title: "很强的手机AI助手 Operit.apk", url: "https://pan.quark.cn/s/319e8c6ef62f", category: "安卓软件", source: "夸克网盘" },
  { title: "手机终端 termux-app_v0.118.2.apk", url: "https://pan.quark.cn/s/a3247b38cd4a", category: "安卓软件", source: "夸克网盘" },
  { title: "手机迅雷下载 Gopeed-v1.7.0-android.apk", url: "https://pan.quark.cn/s/59103e447337", category: "安卓软件", source: "夸克网盘" },
  { title: "搞快点 gkd-v1.8.0.apk", url: "https://pan.quark.cn/s/257333d88e86", category: "安卓软件", source: "夸克网盘" },
  { title: "看漫画 copymanga拷贝漫画2.3.1.apk", url: "https://pan.quark.cn/s/c0f300f68841", category: "安卓软件", source: "夸克网盘" },
  { title: "视频下载工具 Seal-1.13.1.apk", url: "https://pan.quark.cn/s/885fce5efc48", category: "安卓软件", source: "夸克网盘", note: "设置可填cookie" },
  { title: "追番用 Kazumi_android_1.6.0.apk", url: "https://pan.quark.cn/s/c0757898c978", category: "安卓软件", source: "夸克网盘" },

  // ===== 游戏 (108) =====
  { title: "A 奥日系列合集", url: "https://pan.quark.cn/s/ce019abafe4c", category: "游戏", source: "夸克网盘" },
  { title: "A 奥特曼系列合集", url: "https://pan.quark.cn/s/d5dbd7e28a32", category: "游戏", source: "夸克网盘" },
  { title: "A 安娜的怪物农场", url: "https://pan.quark.cn/s/efae29c5347a", category: "游戏", source: "夸克网盘" },
  { title: "B 冰与火之舞 PC+手机", url: "https://pan.quark.cn/s/e994e39a73ad", category: "游戏", source: "夸克网盘" },
  { title: "B 壁纸引擎；Wallpaper Engine", url: "https://pan.quark.cn/s/4edfaade3758", category: "游戏", source: "夸克网盘" },
  { title: "B 崩溃大陆2【PC+安卓+苹果】", url: "https://pan.quark.cn/s/a7d2288ff40c", category: "游戏", source: "夸克网盘" },
  { title: "B 波比的游戏时间", url: "https://pan.quark.cn/s/8a5b8f69255d", category: "游戏", source: "夸克网盘" },
  { title: "B 病娇模拟器", url: "https://pan.quark.cn/s/d3983cae605f", category: "游戏", source: "夸克网盘" },
  { title: "B病院物语", url: "https://pan.quark.cn/s/2eccb914d061", category: "游戏", source: "夸克网盘" },
  { title: "C 刺客信条3重置版", url: "https://pan.quark.cn/s/9f8b9d260c96", category: "游戏", source: "夸克网盘" },
  { title: "C 刺客信条：叛逆者合集", url: "https://pan.quark.cn/s/12ec1f3a64c2", category: "游戏", source: "夸克网盘" },
  { title: "C 城市天际线2（都市天际线）", url: "https://pan.quark.cn/s/c12048e5ee95", category: "游戏", source: "夸克网盘" },
  { title: "C 穿越机模拟器", url: "https://pan.quark.cn/s/6ef8a63d8d6d", category: "游戏", source: "夸克网盘" },
  { title: "C 茶杯头Cuphead PC+手机", url: "https://pan.quark.cn/s/649aa657b4c9", category: "游戏", source: "夸克网盘" },
  { title: "C 超市模拟器 PC+手机", url: "https://pan.quark.cn/s/318aa3a8dae6", category: "游戏", source: "夸克网盘" },
  { title: "C 超级兔子人", url: "https://pan.quark.cn/s/1407d448f406", category: "游戏", source: "夸克网盘" },
  { title: "C 超级兔子人 PC+手机", url: "https://pan.quark.cn/s/1c53f17edc6c", category: "游戏", source: "夸克网盘" },
  { title: "C 超级马里奥 奥德赛", url: "https://pan.quark.cn/s/3c9598d60146", category: "游戏", source: "夸克网盘" },
  { title: "C 超级马里奥 赛车8豪华版", url: "https://pan.quark.cn/s/9efc710cf5e1", category: "游戏", source: "夸克网盘" },
  { title: "C 超级马里奥兄弟 惊奇", url: "https://pan.quark.cn/s/4fecc61ee995", category: "游戏", source: "夸克网盘" },
  { title: "C 车祸模拟器 联机版", url: "https://pan.quark.cn/s/3a23e8066c96", category: "游戏", source: "夸克网盘" },
  { title: "Cat Quest I+II 猫咪斗恶龙 1+2", url: "https://pan.quark.cn/s/c413b25048cb", category: "游戏", source: "夸克网盘" },
  { title: "D 东方夜雀食堂 PC+手机", url: "https://pan.quark.cn/s/047fe41a00bf", category: "游戏", source: "夸克网盘" },
  { title: "D 动物森友会 电脑+手机", url: "https://pan.quark.cn/s/26b209ffa78b", category: "游戏", source: "夸克网盘" },
  { title: "D 大头菜小子银行大冒险", url: "https://pan.quark.cn/s/ab6c94142c08", category: "游戏", source: "夸克网盘" },
  { title: "DarkandDarker 越来越黑暗", url: "https://pan.quark.cn/s/a5f1c3651904", category: "游戏", source: "夸克网盘" },
  { title: "DirectX修复工具增强版 DirectX Repair V4.3.7z", url: "https://pan.quark.cn/s/8217c7defd9e", category: "游戏", source: "夸克网盘", note: "dll修复工具" },
  { title: "F 愤怒的小鸟2最新版", url: "https://pan.quark.cn/s/57e13034cb43", category: "游戏", source: "夸克网盘" },
  { title: "F 方舟：生存进化", url: "https://pan.quark.cn/s/839e69e5778f", category: "游戏", source: "夸克网盘" },
  { title: "F 犯罪现场清理", url: "https://pan.quark.cn/s/efa99c84837e", category: "游戏", source: "夸克网盘" },
  { title: "F 飞机大厨合集", url: "https://pan.quark.cn/s/3976469534ba", category: "游戏", source: "夸克网盘" },
  { title: "F 飞行模拟器", url: "https://pan.quark.cn/s/f433bec0d4ff", category: "游戏", source: "夸克网盘" },
  { title: "F浮岛物语", url: "https://pan.quark.cn/s/5e039e596a01", category: "游戏", source: "夸克网盘" },
  { title: "G GTA5 超清整合版", url: "https://pan.quark.cn/s/55da0559a4c1", category: "游戏", source: "夸克网盘" },
  { title: "G 鬼谷八荒 电脑➕手机", url: "https://pan.quark.cn/s/57a62a427963", category: "游戏", source: "夸克网盘" },
  { title: "H 幻兽帕鲁", url: "https://pan.quark.cn/s/1c283440fcbf", category: "游戏", source: "夸克网盘" },
  { title: "H 海上小镇(1)", url: "https://pan.quark.cn/s/461e40102b6a", category: "游戏", source: "夸克网盘" },
  { title: "H 海绵宝宝大闹蟹堡王（先点右下角保存后下载）", url: "https://pan.quark.cn/s/bfe8c0955665", category: "游戏", source: "夸克网盘" },
  { title: "H 火山的女儿", url: "https://pan.quark.cn/s/8a382f439117", category: "游戏", source: "夸克网盘" },
  { title: "H 胡闹厨房1和2（分手厨房）", url: "https://pan.quark.cn/s/aa4eaa759619", category: "游戏", source: "夸克网盘" },
  { title: "H 荒野大镖客（手机版➕电脑版）", url: "https://pan.quark.cn/s/4fec42138628", category: "游戏", source: "夸克网盘" },
  { title: "J 禁闭求生（PC➕手机）", url: "https://pan.quark.cn/s/51540a7cd473", category: "游戏", source: "夸克网盘" },
  { title: "J 纪念碑谷合集", url: "https://pan.quark.cn/s/e7dbafcfd678", category: "游戏", source: "夸克网盘" },
  { title: "J 节奏盒子", url: "https://pan.quark.cn/s/6ca54288f071", category: "游戏", source: "夸克网盘" },
  { title: "J 金铲铲无限金币版", url: "https://pan.quark.cn/s/b29fd6657a0d", category: "游戏", source: "夸克网盘" },
  { title: "J 饥荒（苹果+安卓+电脑）", url: "https://pan.quark.cn/s/204f64646979", category: "游戏", source: "夸克网盘" },
  { title: "K kards 手机版", url: "https://pan.quark.cn/s/28644887edc0", category: "游戏", source: "夸克网盘" },
  { title: "K 可口的咖啡", url: "https://pan.quark.cn/s/fb2fed863e85", category: "游戏", source: "夸克网盘" },
  { title: "K 可口的披萨", url: "https://pan.quark.cn/s/64cd14c92f44", category: "游戏", source: "夸克网盘" },
  { title: "K 空洞骑士", url: "https://pan.quark.cn/s/934e1cc4b67b", category: "游戏", source: "夸克网盘" },
  { title: "L 洛克王国", url: "https://pan.quark.cn/s/993321718973", category: "游戏", source: "夸克网盘" },
  { title: "L 灵魂摆渡人（手游）", url: "https://pan.quark.cn/s/302f2625aced", category: "游戏", source: "夸克网盘" },
  { title: "L 老爹合集（先点右下角保存，后下载）", url: "https://pan.quark.cn/s/772e92c14f59", category: "游戏", source: "夸克网盘" },
  { title: "Limbo", url: "https://pan.quark.cn/s/21b150cb7b72", category: "游戏", source: "夸克网盘" },
  { title: "M 咩咩启示录（手机+电脑）", url: "https://pan.quark.cn/s/75c7c54fee4d", category: "游戏", source: "夸克网盘" },
  { title: "M 喵斯快跑", url: "https://pan.quark.cn/s/29ad22d6a981", category: "游戏", source: "夸克网盘" },
  { title: "M 木筏求生", url: "https://pan.quark.cn/s/9c118676e403", category: "游戏", source: "夸克网盘" },
  { title: "M 模拟人生4", url: "https://pan.quark.cn/s/2479e9fa09d0", category: "游戏", source: "夸克网盘" },
  { title: "M 米加小镇世界（点进来）", url: "https://pan.quark.cn/s/efc82e96c59c", category: "游戏", source: "夸克网盘" },
  { title: "M 米塔Miside", url: "https://pan.quark.cn/s/ec7697b1fea8", category: "游戏", source: "夸克网盘" },
  { title: "M 露玛岛 v1.19中文联机版", url: "https://pan.quark.cn/s/e7a32980816a", category: "游戏", source: "夸克网盘" },
  { title: "N BA 2k24和25手机版", url: "https://pan.quark.cn/s/16144b2c5a91", category: "游戏", source: "夸克网盘" },
  { title: "N NB实验室", url: "https://pan.quark.cn/s/2257dd3e985d", category: "游戏", source: "夸克网盘" },
  { title: "N 女神异闻录：皇家版 PC+手机", url: "https://pan.quark.cn/s/c80a705fc2d8", category: "游戏", source: "夸克网盘" },
  { title: "N 暖雪v3.1.0.1 整合终业DLC PC+手机", url: "https://pan.quark.cn/s/a96b549f651f", category: "游戏", source: "夸克网盘" },
  { title: "Q 奇妙创意世界", url: "https://pan.quark.cn/s/63ec58dbe325", category: "游戏", source: "夸克网盘" },
  { title: "Q 拳皇合集 94 95 96 97 98 99 20k 2k01 2k02 2k03", url: "https://pan.quark.cn/s/3a961c2d4689", category: "游戏", source: "夸克网盘" },
  { title: "Q 潜水员戴夫 全DLC PC+手机", url: "https://pan.quark.cn/s/ad245d55b622", category: "游戏", source: "夸克网盘" },
  { title: "R 人类一败涂地 电脑➕手机", url: "https://pan.quark.cn/s/b63287baad61", category: "游戏", source: "夸克网盘" },
  { title: "S 世界盒子PC+手机", url: "https://pan.quark.cn/s/e69552300338", category: "游戏", source: "夸克网盘" },
  { title: "S 双人成行 手机+电脑", url: "https://pan.quark.cn/s/9a9623c582ad", category: "游戏", source: "夸克网盘" },
  { title: "S 双影奇境（新游推荐）", url: "https://pan.quark.cn/s/f81d6acd79e1", category: "游戏", source: "夸克网盘" },
  { title: "S 塞尔达传说合集【手机+电脑】", url: "https://pan.quark.cn/s/2773d02d47d2", category: "游戏", source: "夸克网盘" },
  { title: "S 死亡细胞PC+安卓", url: "https://pan.quark.cn/s/b912c71aaba4", category: "游戏", source: "夸克网盘" },
  { title: "S 死无对证（无广免费版）", url: "https://pan.quark.cn/s/6ece81b99239", category: "游戏", source: "夸克网盘" },
  { title: "S 沙威玛传奇（手机+电脑）", url: "https://pan.quark.cn/s/49079c574f06", category: "游戏", source: "夸克网盘" },
  { title: "S 沙雕培根（先点右下角保存，后下载）", url: "https://pan.quark.cn/s/2a3d1f4bc0eb", category: "游戏", source: "夸克网盘" },
  { title: "S 生化危机合集1-6（手机+电脑）", url: "https://pan.quark.cn/s/e06a00447140", category: "游戏", source: "夸克网盘" },
  { title: "S 谁是你爸爸（手机版电脑版游戏）", url: "https://pan.quark.cn/s/01e44458edc1", category: "游戏", source: "夸克网盘" },
  { title: "S 速度之星", url: "https://pan.quark.cn/s/d8678b52aa1e", category: "游戏", source: "夸克网盘" },
  { title: "S生化危机6PC➕手机", url: "https://pan.quark.cn/s/3da1549c73f9", category: "游戏", source: "夸克网盘" },
  { title: "T 土豆兄弟 PC+手机", url: "https://pan.quark.cn/s/9b1a494c360f", category: "游戏", source: "夸克网盘" },
  { title: "T 托卡生活世界", url: "https://pan.quark.cn/s/a902ffbd18d4", category: "游戏", source: "夸克网盘" },
  { title: "T 泰拉瑞亚PC+安卓➕苹果", url: "https://pan.quark.cn/s/55fe299a8120", category: "游戏", source: "夸克网盘" },
  { title: "TCG卡牌商店模拟器《切记先单独保存再免费下载》", url: "https://pan.quark.cn/s/1c4a36b37b37", category: "游戏", source: "夸克网盘" },
  { title: "W 外国山海经", url: "https://pan.quark.cn/s/1bd3d7a2317d", category: "游戏", source: "夸克网盘" },
  { title: "W 完蛋我被美女包围了", url: "https://pan.quark.cn/s/f417d16adc65", category: "游戏", source: "夸克网盘" },
  { title: "W 我是猫（先保存在下载）", url: "https://pan.quark.cn/s/17f29db2da71", category: "游戏", source: "夸克网盘" },
  { title: "W 我的世界", url: "https://pan.quark.cn/s/a3bb2f3bf804", category: "游戏", source: "夸克网盘" },
  { title: "W 文明6+7 PC+手机", url: "https://pan.quark.cn/s/1ba49ef6265b", category: "游戏", source: "夸克网盘" },
  { title: "X 侠盗猎车全系列手机➕电脑", url: "https://pan.quark.cn/s/2ee32439607e", category: "游戏", source: "夸克网盘" },
  { title: "X 小小梦魇系列", url: "https://pan.quark.cn/s/dbbbd4a7a67b", category: "游戏", source: "夸克网盘" },
  { title: "X 星之卡比系列", url: "https://pan.quark.cn/s/67d340d05c20", category: "游戏", source: "夸克网盘" },
  { title: "X 星露谷物语", url: "https://pan.quark.cn/s/fa6292c1fa3b", category: "游戏", source: "夸克网盘" },
  { title: "X 锈湖合集（解谜游戏）", url: "https://pan.quark.cn/s/82414d45a29f", category: "游戏", source: "夸克网盘" },
  { title: "Y 樱花校园模拟器", url: "https://pan.quark.cn/s/2235a6be7a89", category: "游戏", source: "夸克网盘" },
  { title: "Z 只只大冒险", url: "https://pan.quark.cn/s/e0f279692381", category: "游戏", source: "夸克网盘" },
  { title: "Z 咒语旅团", url: "https://pan.quark.cn/s/05e577b71930", category: "游戏", source: "夸克网盘" },
  { title: "Z 植物大战僵尸合集", url: "https://pan.quark.cn/s/615c2c7505ab", category: "游戏", source: "夸克网盘" },
  { title: "directx_11.exe", url: "https://pan.quark.cn/s/86d7096e678f", category: "游戏", source: "夸克网盘" },
  { title: "下载工具 fdm_x64_setup.exe", url: "https://pan.quark.cn/s/561d5932a6ae", category: "游戏", source: "夸克网盘", note: "拉满网速的下载工具" },
  { title: "奥日与黑暗森林", url: "https://pan.quark.cn/s/132dcbfa2544", category: "游戏", source: "夸克网盘" },
  { title: "幽灵线 东京 GhostwireTokyo", url: "https://pan.quark.cn/s/da4594d3423d", category: "游戏", source: "夸克网盘" },
  { title: "无双大蛇3：终极版", url: "https://pan.quark.cn/s/74c038e04773", category: "游戏", source: "夸克网盘" },
  { title: "植物精灵 (Botanicula)", url: "https://pan.quark.cn/s/0d1f310ac909", category: "游戏", source: "夸克网盘" },
  { title: "游戏加速 雷神加速器LeiGodSetup.11.2.0.6.exe", url: "https://pan.quark.cn/s/97d1de1dca6f", category: "游戏", source: "夸克网盘", note: "邀请码 SS9zfO · ISO文件不用解压，直接双击挂载即可" },
  { title: "真三国无双：起源 v1.0.0.7 预购特典 全DLC 支持手柄 官方豪华中文版", url: "https://pan.quark.cn/s/bcb6f97aa461", category: "游戏", source: "夸克网盘" },
  { title: "米塔(MiSide) v0.9 官方中文 日语配音", url: "https://pan.quark.cn/s/b4fa634d68a5", category: "游戏", source: "夸克网盘" },

  // ===== 漫画小说 (70) =====
  // --- 漫画 ---
  { title: "8月31日的長夏 _ 伊藤一角", url: "https://pan.quark.cn/s/e8dab4661ec0", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "Keroro军曹", url: "https://pan.quark.cn/s/c0b983a9c61a", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "MÄR 魔兵传奇", url: "https://pan.baidu.com/s/1V6FI_EbsnmucKCT4J4q4dA?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "一胜千金", url: "https://pan.quark.cn/s/f45e60ddfe7c", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "不要欺负我，长瀞同学", url: "https://pan.baidu.com/s/1bNGmZfIyP5CWAYTpxjxb5g?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "与日本最可爱的女高中生同居", url: "https://pan.quark.cn/s/f818221f1ed9", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "为何我总是成为s级美少女们的话题", url: "https://pan.quark.cn/s/24d4e566ff20", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "会长是女仆大人", url: "https://pan.quark.cn/s/86d0366c98fd", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "你是地雷嗎？地原同學", url: "https://pan.quark.cn/s/74ffbd53a83a", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "侵略！乌贼娘", url: "https://pan.quark.cn/s/d641ad451776", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "午夜心旋律 _ 五十嵐正邦", url: "https://pan.quark.cn/s/95e2cf962fdf", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "半透明女友", url: "https://pan.quark.cn/s/50846f8f6bac", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "即便在现实世界也要让我幸福哦", url: "https://pan.quark.cn/s/9ddf5e5bece7", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "向我提要求的雪平同学", url: "https://pan.quark.cn/s/96410c8ed39a", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "吾輩的男友是笨蛋", url: "https://pan.quark.cn/s/9401d95cb4fe", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "命运石之门", url: "https://pan.quark.cn/s/08c4e1f8d572", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "安达与岛村", url: "https://pan.quark.cn/s/b978243b7721", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "完全沒有戀愛感情的青梅竹馬", url: "https://pan.quark.cn/s/99d251f1a9a5", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "干物妹！小埋", url: "https://pan.quark.cn/s/1a1b04f46158", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "式守同学不只可爱而已", url: "https://pan.quark.cn/s/521edcada91b", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "当我转生获得空间系统，决定把它填满垃圾", url: "https://pan.quark.cn/s/cc2029476afe", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "徒然喜欢你", url: "https://pan.quark.cn/s/1d64b42396b9", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "從路人開始的探索英雄譚 _ てりてりお", url: "https://pan.quark.cn/s/71ec8e4b443d", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "想结束这场[我爱你]的游戏", url: "https://pan.quark.cn/s/e60affdd42f9", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "我的妹妹(学妹)哪有这么可爱 漫画", url: "https://pan.quark.cn/s/7a6f0b536b94", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "暗杀教室", url: "https://pan.baidu.com/s/1UvPMVwmQr4fb4Mow_K-3PQ?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "未来日记 漫画", url: "https://pan.baidu.com/s/1wcKmKDFZIF-R7MAsmL2FSg?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "死亡笔记", url: "https://pan.baidu.com/s/1HhyHa9LccD8460kc9_QeYQ?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "游戏王全彩", url: "https://pan.baidu.com/s/1kGv-yzDWTJ3ZFQx10_GmZA?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "琉璃龙龙", url: "https://pan.quark.cn/s/ff68854eadd0", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "瓜熟蒂落", url: "https://pan.quark.cn/s/d5294fb2d2c2", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "甜甜私房猫(全彩版12卷完结)", url: "https://pan.quark.cn/s/2c218edcc114", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "美少女战士 漫画画集", url: "https://pan.baidu.com/s/1rFB3Jxg2QzyQi9UDaziPcQ?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "虛構推理 _ 城平京", url: "https://pan.quark.cn/s/c26fcb5cda6a", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "被女孩子逆推不行嗎？", url: "https://pan.quark.cn/s/9d8a9df85e23", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "路人超能100（灵能百分百）", url: "https://pan.baidu.com/s/14q3T0uum0giE3t_7VEJbkw?pwd=ypux", category: "漫画小说", source: "百度网盘", code: "ypux", section: "漫画" },
  { title: "躲在超市後門抽烟的兩人", url: "https://pan.quark.cn/s/2154ff4fefb3", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "醉酒千金不知英雄身份", url: "https://pan.quark.cn/s/f09268153bad", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "關於轉生後只有燈里變成史萊姆這檔事", url: "https://pan.quark.cn/s/5ecc2b1260b5", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "魔王學院的不適合者 ～史上最強的魔王始祖、轉生之後入學到子孫們的學校～", url: "https://pan.quark.cn/s/b0ef17627431", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  { title: "黄昏公主与恋爱乌鸦", url: "https://pan.quark.cn/s/697bd4eb27c5", category: "漫画小说", source: "夸克网盘", section: "漫画" },
  // --- 轻小说 ---
  { title: "GAMERS电玩咖", url: "https://pan.quark.cn/s/7615b3f7cbdc", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "不正经的魔术讲师与禁忌教典", url: "https://pan.quark.cn/s/43250adb082b", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "不死侦探冷堂红叶", url: "https://pan.quark.cn/s/affaefcbe8bd", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "义妹生活", url: "https://pan.quark.cn/s/540232f5918e", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "全知读者视角", url: "https://pan.quark.cn/s/75e6750df0ca", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "公爵千金的家庭教师", url: "https://pan.quark.cn/s/659822848d91", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "和前妻重返同学时代", url: "https://pan.quark.cn/s/51b2ee9f6767", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "带着智慧型手机闯荡异世界", url: "https://pan.quark.cn/s/35154280981a", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "恋爱无法用双子除尽", url: "https://pan.quark.cn/s/2992117afe1b", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "想要成为勇者的少女，与理应成为勇者的她", url: "https://pan.quark.cn/s/ff19c7153c69", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "成为阳光系的我专属的青春至上主义", url: "https://pan.quark.cn/s/ebaf6778c666", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "我的公寓变成了地下城，那就驯服最强怪物轻松攻略吧", url: "https://pan.quark.cn/s/4ab0dc4d2ef8", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "把班上的孤单辣妹带回家改造成清纯美女的故事", url: "https://pan.quark.cn/s/9922e43d82df", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "时隔10年重逢，臭小鬼长成了清纯美少女JK", url: "https://pan.quark.cn/s/74243d6020f8", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "朋友的妹妹只喜欢烦我", url: "https://pan.quark.cn/s/d88aaa76e955", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "沉默魔女的秘密", url: "https://pan.quark.cn/s/e9878daff141", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "班上的原偶像", url: "https://pan.quark.cn/s/2ea74d76359e", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "男女之间存在纯友情吗", url: "https://pan.quark.cn/s/2ef4f4b7ef28", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "终末停滞委员会", url: "https://pan.quark.cn/s/c511099ab9a2", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "网路上的『本命』跟现实中的『本命』都搬到隔壁来了", url: "https://pan.quark.cn/s/071acd934bd0", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "被一群美少女英靈培育的我，成為人類王牌這件事", url: "https://pan.quark.cn/s/047ba7545204", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "请问您的胖次需要加热吗？", url: "https://pan.quark.cn/s/dd4950e443df", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "转生公主与天才千金的魔法革命", url: "https://pan.quark.cn/s/02d96d2c93a5", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "轮班邂逅录～那位模特同学只在我当值时出现～", url: "https://pan.quark.cn/s/efe728d26b17", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "这份恋情，与其未来。", url: "https://pan.quark.cn/s/d13de12e296a", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "通往夏天的隧道，再见的出口", url: "https://pan.quark.cn/s/f908fe201880", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "银砂糖师与黑妖精", url: "https://pan.quark.cn/s/edaf52333042", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "霸剑皇姬阿尔缇娜", url: "https://pan.quark.cn/s/140653bd7d50", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
  { title: "飘在班上的宇良良川同学", url: "https://pan.quark.cn/s/21027887c3b8", category: "漫画小说", source: "夸克网盘", section: "轻小说" },
];

var SECTION_TIPS = {
  "漫画小说|漫画": "轻小说在楼下 · 如果这里没有可以到动漫合集链接找找",
  "剧集|少量电影": "部分为bt链接，夸克可以直接解析下载",
  "学习资料|各类教材": "百度云盘有云打印功能，会比较便宜"
};